/*
  MSSQL Analysis · Documentation · Conversion Code Generation Agent Platform
  Platform DB DDL Draft v2 (SQL Server / T-SQL 기준)

  주의:
  - 업로드 기준 문서에는 플랫폼 운영 DBMS가 명시되어 있지 않다.
  - 아래 DDL은 실행 가능성을 높이기 위해 SQL Server(T-SQL) 기준으로 제시한 권장 초안이다.
  - 대용량 본문(content, analysis_json, payload_json 등)은 Object Storage 분리 저장을 전제로 content_ref를 함께 둔다.
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* =========================
   auth
   ========================= */
CREATE TABLE dbo.AUTH_USERS (
    USR_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    LGN_ID NVARCHAR(100) NOT NULL,
    USR_NM NVARCHAR(200) NOT NULL,
    EML_ADR NVARCHAR(320) NULL,
    STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUTH_USERS PRIMARY KEY CLUSTERED (USR_ID),
    CONSTRAINT UQ_AUTH_USERS_LOGIN_ID UNIQUE (LGN_ID),
    CONSTRAINT CHK_AUTH_USERS_STATUS_CD CHECK (STAT_CD IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);
GO

CREATE TABLE dbo.AUTH_ROLES (
    AUTH_GRP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    AUTH_GRP_NM NVARCHAR(100) NOT NULL,
    AUTH_GRP_DESC NVARCHAR(500) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUTH_ROLES PRIMARY KEY CLUSTERED (AUTH_GRP_ID),
    CONSTRAINT UQ_AUTH_ROLES_ROLE_NAME UNIQUE (AUTH_GRP_NM)
);
GO

CREATE TABLE dbo.AUTH_USER_ROLES (
    USR_AUTH_GRP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    USR_ID UNIQUEIDENTIFIER NOT NULL,
    AUTH_GRP_ID UNIQUEIDENTIFIER NOT NULL,
    GRT_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    GRT_USR_ID UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_AUTH_USER_ROLES PRIMARY KEY CLUSTERED (USR_AUTH_GRP_ID),
    CONSTRAINT UQ_AUTH_USER_ROLES UNIQUE (USR_ID, AUTH_GRP_ID),
    CONSTRAINT FK_AUTH_USER_ROLES_USER FOREIGN KEY (USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_AUTH_USER_ROLES_ROLE FOREIGN KEY (AUTH_GRP_ID) REFERENCES dbo.AUTH_ROLES(AUTH_GRP_ID),
    CONSTRAINT FK_AUTH_USER_ROLES_GRANTED_BY FOREIGN KEY (GRT_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   core
   ========================= */
CREATE TABLE dbo.CORE_DB_PROFILES (
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    DB_PRFL_NM NVARCHAR(150) NOT NULL,
    DBMS_TP_CD NVARCHAR(30) NOT NULL DEFAULT 'MSSQL',
    HOST_NM NVARCHAR(255) NOT NULL,
    PORT_NO INT NOT NULL,
    DB_NM NVARCHAR(255) NOT NULL,
    CONNECTION_META_JSON NVARCHAR(MAX) NULL,
    SCRT_REF_ID NVARCHAR(255) NULL,
    READ_ONLY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_USR_ID UNIQUEIDENTIFIER NULL,
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_DB_PROFILES PRIMARY KEY CLUSTERED (DB_PRFL_ID),
    CONSTRAINT UQ_CORE_DB_PROFILES_PROFILE_NAME UNIQUE (DB_PRFL_NM),
    CONSTRAINT CHK_CORE_DB_PROFILES_DB_TYPE_CD CHECK (DBMS_TP_CD IN ('MSSQL')),
    CONSTRAINT CHK_CORE_DB_PROFILES_READ_ONLY_YN CHECK (READ_ONLY_YN IN ('Y')),
    CONSTRAINT CHK_CORE_DB_PROFILES_STATUS_CD CHECK (STAT_CD IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT FK_CORE_DB_PROFILES_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_CORE_DB_PROFILES_UPDATED_BY FOREIGN KEY (UPD_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TABLE dbo.CORE_DB_PROFILE_ALLOWED_SCHEMAS (
    DB_PRFL_SCHM_MAP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL,
    SCHM_NM NVARCHAR(128) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_DB_PROFILE_ALLOWED_SCHEMAS PRIMARY KEY CLUSTERED (DB_PRFL_SCHM_MAP_ID),
    CONSTRAINT UQ_CORE_DB_PROFILE_ALLOWED_SCHEMAS UNIQUE (DB_PRFL_ID, SCHM_NM),
    CONSTRAINT FK_CORE_DB_PROFILE_ALLOWED_SCHEMAS_PROFILE FOREIGN KEY (DB_PRFL_ID) REFERENCES dbo.CORE_DB_PROFILES(DB_PRFL_ID)
);
GO

CREATE TABLE dbo.CORE_WORK_REQUESTS (
    REQ_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    REQ_TP_CD NVARCHAR(30) NOT NULL,
    REQR_USR_ID UNIQUEIDENTIFIER NOT NULL,
    RVWR_GRP_NM NVARCHAR(100) NULL,
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL,
    TRGT_PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    DESIRED_RSLT_JSON NVARCHAR(MAX) NULL,
    OPTN_PAYLD_JSON NVARCHAR(MAX) NULL,
    CUR_STAT_CD NVARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    TRC_ID NVARCHAR(100) NULL,
    SUBMITTED_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_WORK_REQUESTS PRIMARY KEY CLUSTERED (REQ_ID),
    CONSTRAINT CHK_CORE_WORK_REQUESTS_REQUEST_TYPE_CD CHECK (REQ_TP_CD IN ('SP_ANALYSIS', 'SCHEMA_SEARCH', 'CODE_GENERATION')),
    CONSTRAINT CHK_CORE_WORK_REQUESTS_CURRENT_STATUS_CD CHECK (CUR_STAT_CD IN ('SUBMITTED', 'COLLECTING_METADATA', 'ANALYZING', 'GENERATING', 'VALIDATING', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', 'CANCELED')),
    CONSTRAINT FK_CORE_WORK_REQUESTS_REQUESTER FOREIGN KEY (REQR_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_CORE_WORK_REQUESTS_DB_PROFILE FOREIGN KEY (DB_PRFL_ID) REFERENCES dbo.CORE_DB_PROFILES(DB_PRFL_ID)
);
GO

CREATE TABLE dbo.CORE_JOBS (
    JOB_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    REQ_ID UNIQUEIDENTIFIER NOT NULL,
    CUR_STAT_CD NVARCHAR(30) NOT NULL,
    START_DTM DATETIME2(3) NULL,
    END_DTM DATETIME2(3) NULL,
    CUR_STEP_TP_CD NVARCHAR(30) NULL,
    SNAP_ID UNIQUEIDENTIFIER NULL,
    RGST_BINDING_JSON NVARCHAR(MAX) NULL,
    WRKR_REF_ID NVARCHAR(200) NULL,
    ERR_CD NVARCHAR(100) NULL,
    ERR_CNTNT NVARCHAR(2000) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_JOBS PRIMARY KEY CLUSTERED (JOB_ID),
    CONSTRAINT CHK_CORE_JOBS_CURRENT_STATUS_CD CHECK (CUR_STAT_CD IN ('SUBMITTED', 'COLLECTING_METADATA', 'ANALYZING', 'GENERATING', 'VALIDATING', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', 'CANCELED')),
    CONSTRAINT CHK_CORE_JOBS_CURRENT_STEP_TYPE_CD CHECK (CUR_STEP_TP_CD IS NULL OR CUR_STEP_TP_CD IN ('COLLECT_METADATA', 'ANALYZE', 'GENERATE', 'VALIDATE', 'REVIEW', 'PUBLISH')),
    CONSTRAINT FK_CORE_JOBS_REQUEST FOREIGN KEY (REQ_ID) REFERENCES dbo.CORE_WORK_REQUESTS(REQ_ID)
);
GO

CREATE TABLE dbo.CORE_JOB_STEPS (
    STEP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    STEP_TP_CD NVARCHAR(30) NOT NULL,
    STAT_CD NVARCHAR(20) NOT NULL,
    START_DTM DATETIME2(3) NULL,
    END_DTM DATETIME2(3) NULL,
    RETRY_CNT INT NOT NULL DEFAULT 0,
    STEP_JSON NVARCHAR(MAX) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_JOB_STEPS PRIMARY KEY CLUSTERED (STEP_ID),
    CONSTRAINT CHK_CORE_JOB_STEPS_STEP_TYPE_CD CHECK (STEP_TP_CD IN ('COLLECT_METADATA', 'ANALYZE', 'GENERATE', 'VALIDATE', 'REVIEW', 'PUBLISH')),
    CONSTRAINT CHK_CORE_JOB_STEPS_STATUS_CD CHECK (STAT_CD IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT FK_CORE_JOB_STEPS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

/* =========================
   registry
   ========================= */
CREATE TABLE dbo.REGISTRY_ITEMS (
    RGST_ITEM_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ITEM_TP_CD NVARCHAR(30) NOT NULL,
    ITEM_NM NVARCHAR(150) NOT NULL,
    ITEM_DESC NVARCHAR(1000) NULL,
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_REGISTRY_ITEMS PRIMARY KEY CLUSTERED (RGST_ITEM_ID),
    CONSTRAINT UQ_REGISTRY_ITEMS UNIQUE (ITEM_TP_CD, ITEM_NM),
    CONSTRAINT CHK_REGISTRY_ITEMS_KIND_CD CHECK (ITEM_TP_CD IN ('PROMPT', 'TEMPLATE', 'MODEL_POLICY', 'DB_PROFILE_POLICY')),
    CONSTRAINT FK_REGISTRY_ITEMS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TABLE dbo.REGISTRY_VERSIONS (
    RGST_VER_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    RGST_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
    VER_SEQ_NO INT NOT NULL,
    CNTNT_TP_CD NVARCHAR(20) NOT NULL,
    CNTNT_REF_ID NVARCHAR(500) NULL,
    CNTNT_TXT NVARCHAR(MAX) NULL,
    CHK_SUM_SHA256_VAL NVARCHAR(64) NULL,
    PBLC_YN CHAR(1) NOT NULL DEFAULT 'N',
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    PBLC_DTM DATETIME2(3) NULL,
    PBLC_USR_ID UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_REGISTRY_VERSIONS PRIMARY KEY CLUSTERED (RGST_VER_ID),
    CONSTRAINT UQ_REGISTRY_VERSIONS UNIQUE (RGST_ITEM_ID, VER_SEQ_NO),
    CONSTRAINT CHK_REGISTRY_VERSIONS_CONTENT_TYPE_CD CHECK (CNTNT_TP_CD IN ('TEXT', 'YAML', 'JSON', 'MARKDOWN')),
    CONSTRAINT CHK_REGISTRY_VERSIONS_PUBLISHED_YN CHECK (PBLC_YN IN ('Y', 'N')),
    CONSTRAINT FK_REGISTRY_VERSIONS_ITEM FOREIGN KEY (RGST_ITEM_ID) REFERENCES dbo.REGISTRY_ITEMS(RGST_ITEM_ID),
    CONSTRAINT FK_REGISTRY_VERSIONS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_REGISTRY_VERSIONS_PUBLISHED_BY FOREIGN KEY (PBLC_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   metadata
   ========================= */
CREATE TABLE dbo.METADATA_SNAPSHOTS (
    SNAP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL,
    SNAP_SCOPE_CD NVARCHAR(30) NOT NULL,
    OBJ_SCOPE_JSON NVARCHAR(MAX) NULL,
    SRC_HASH_VAL NVARCHAR(128) NULL,
    CAPTURED_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CAPTURED_JOB_ID UNIQUEIDENTIFIER NULL,
    REM_CNTNT NVARCHAR(1000) NULL,
    CONSTRAINT PK_METADATA_SNAPSHOTS PRIMARY KEY CLUSTERED (SNAP_ID),
    CONSTRAINT CHK_METADATA_SNAPSHOTS_SCOPE_CD CHECK (SNAP_SCOPE_CD IN ('LATEST', 'PINNED', 'JOB_BOUND')),
    CONSTRAINT FK_METADATA_SNAPSHOTS_PROFILE FOREIGN KEY (DB_PRFL_ID) REFERENCES dbo.CORE_DB_PROFILES(DB_PRFL_ID),
    CONSTRAINT FK_METADATA_SNAPSHOTS_JOB FOREIGN KEY (CAPTURED_JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

CREATE TABLE dbo.METADATA_OBJECT_CACHE (
    OBJ_CACHE_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    SNAP_ID UNIQUEIDENTIFIER NOT NULL,
    OBJ_TP_CD NVARCHAR(30) NOT NULL,
    SCHM_NM NVARCHAR(128) NOT NULL,
    OBJ_NM NVARCHAR(128) NOT NULL,
    LGC_NM NVARCHAR(255) NULL,
    OBJ_DESC NVARCHAR(MAX) NULL,
    NORMALIZED_TERMS_TXT NVARCHAR(MAX) NULL,
    META_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_OBJECT_CACHE PRIMARY KEY CLUSTERED (OBJ_CACHE_ID),
    CONSTRAINT UQ_METADATA_OBJECT_CACHE UNIQUE (SNAP_ID, OBJ_TP_CD, SCHM_NM, OBJ_NM),
    CONSTRAINT CHK_METADATA_OBJECT_CACHE_OBJECT_TYPE_CD CHECK (OBJ_TP_CD IN ('PROCEDURE', 'TABLE', 'COLUMN', 'INDEX', 'PK', 'FK', 'FUNCTION', 'VIEW', 'EXTENDED_PROPERTY')),
    CONSTRAINT FK_METADATA_OBJECT_CACHE_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID)
);
GO

CREATE TABLE dbo.METADATA_DEPENDENCY_EDGES (
    DEPD_EDGE_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    SNAP_ID UNIQUEIDENTIFIER NOT NULL,
    FR_OBJ_TP_CD NVARCHAR(30) NOT NULL,
    FR_SCHM_NM NVARCHAR(128) NOT NULL,
    FR_OBJ_NM NVARCHAR(128) NOT NULL,
    DEPD_TP_CD NVARCHAR(30) NOT NULL,
    TO_OBJ_TP_CD NVARCHAR(30) NOT NULL,
    TO_SCHM_NM NVARCHAR(128) NOT NULL,
    TO_OBJ_NM NVARCHAR(128) NOT NULL,
    EVDC_JSON NVARCHAR(MAX) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_DEPENDENCY_EDGES PRIMARY KEY CLUSTERED (DEPD_EDGE_ID),
    CONSTRAINT CHK_METADATA_DEPENDENCY_EDGES_RELATION_TYPE_CD CHECK (DEPD_TP_CD IN ('READS', 'WRITES', 'CALLS', 'REFERENCES', 'USES_TEMP_TABLE', 'USES_DYNAMIC_SQL')),
    CONSTRAINT FK_METADATA_DEPENDENCY_EDGES_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID)
);
GO

/* =========================
   analysis
   ========================= */
CREATE TABLE dbo.ANALYSIS_RESULTS (
    ANLS_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    SNAP_ID UNIQUEIDENTIFIER NOT NULL,
    TRGT_TP_CD NVARCHAR(30) NOT NULL,
    TRGT_SCHM_NM NVARCHAR(128) NOT NULL,
    TRGT_OBJ_NM NVARCHAR(128) NOT NULL,
    ANLS_STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    ANLS_JSON NVARCHAR(MAX) NOT NULL,
    ANLS_DESC NVARCHAR(2000) NULL,
    CONFIDENCE_CD NVARCHAR(20) NULL,
    CNTNT_REF_ID NVARCHAR(500) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ANALYSIS_RESULTS PRIMARY KEY CLUSTERED (ANLS_ID),
    CONSTRAINT CHK_ANALYSIS_RESULTS_TARGET_TYPE_CD CHECK (TRGT_TP_CD IN ('PROCEDURE', 'TABLE', 'VIEW', 'FUNCTION')),
    CONSTRAINT CHK_ANALYSIS_RESULTS_STATUS_CD CHECK (ANLS_STAT_CD IN ('COMPLETED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT CHK_ANALYSIS_RESULTS_CONFIDENCE_CD CHECK (CONFIDENCE_CD IS NULL OR CONFIDENCE_CD IN ('DETERMINISTIC', 'INFERRED', 'REVIEW_REQUIRED')),
    CONSTRAINT FK_ANALYSIS_RESULTS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID),
    CONSTRAINT FK_ANALYSIS_RESULTS_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID)
);
GO

CREATE TABLE dbo.ANALYSIS_EVIDENCE_REFS (
    ANLS_EVDC_REF_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ANLS_ID UNIQUEIDENTIFIER NOT NULL,
    EVDC_TP_CD NVARCHAR(30) NOT NULL,
    OBJ_REF_ID NVARCHAR(500) NOT NULL,
    LOCATOR_TXT NVARCHAR(1000) NULL,
    CONFIDENCE_CD NVARCHAR(20) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ANALYSIS_EVIDENCE_REFS PRIMARY KEY CLUSTERED (ANLS_EVDC_REF_ID),
    CONSTRAINT CHK_ANALYSIS_EVIDENCE_REFS_EVIDENCE_TYPE_CD CHECK (EVDC_TP_CD IN ('OBJECT', 'COLUMN', 'INDEX', 'CONSTRAINT', 'DEFINITION', 'SNAPSHOT')),
    CONSTRAINT CHK_ANALYSIS_EVIDENCE_REFS_CONFIDENCE_CD CHECK (CONFIDENCE_CD IN ('DETERMINISTIC', 'INFERRED', 'REVIEW_REQUIRED')),
    CONSTRAINT FK_ANALYSIS_EVIDENCE_REFS_ANALYSIS FOREIGN KEY (ANLS_ID) REFERENCES dbo.ANALYSIS_RESULTS(ANLS_ID)
);
GO

/* =========================
   artifact
   ========================= */
CREATE TABLE dbo.ARTIFACTS (
    ARTF_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    ARTF_TP_CD NVARCHAR(40) NOT NULL,
    CUR_STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    CUR_ARTF_VER_ID UNIQUEIDENTIFIER NULL,
    TITL NVARCHAR(300) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACTS PRIMARY KEY CLUSTERED (ARTF_ID),
    CONSTRAINT CHK_ARTIFACTS_TYPE_CD CHECK (ARTF_TP_CD IN ('SP_ANALYSIS_DOC', 'DEPENDENCY_REPORT', 'METADATA_QUERY_RESULT', 'SCHEMA_ENRICHMENT_RESULT', 'MAPPER_XML', 'MAPPER_INTERFACE', 'SERVICE_DRAFT', 'DTO_DRAFT', 'VO_DRAFT', 'MODEL_DRAFT', 'DDL_DRAFT', 'VALIDATION_REPORT', 'APPROVAL_LOG')),
    CONSTRAINT CHK_ARTIFACTS_STATUS_CD CHECK (CUR_STAT_CD IN ('DRAFT', 'VALIDATED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT FK_ARTIFACTS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

CREATE TABLE dbo.ARTIFACT_VERSIONS (
    ARTF_VER_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ARTF_ID UNIQUEIDENTIFIER NOT NULL,
    VER_SEQ_NO INT NOT NULL,
    CNTNT_TP_CD NVARCHAR(20) NOT NULL,
    CNTNT_REF_ID NVARCHAR(500) NULL,
    CNTNT_TXT NVARCHAR(MAX) NULL,
    CHK_SUM_SHA256_VAL NVARCHAR(64) NULL,
    SNAP_ID UNIQUEIDENTIFIER NULL,
    ANLS_ID UNIQUEIDENTIFIER NULL,
    RGST_BINDING_JSON NVARCHAR(MAX) NULL,
    EVDC_JSON NVARCHAR(MAX) NULL,
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACT_VERSIONS PRIMARY KEY CLUSTERED (ARTF_VER_ID),
    CONSTRAINT UQ_ARTIFACT_VERSIONS UNIQUE (ARTF_ID, VER_SEQ_NO),
    CONSTRAINT CHK_ARTIFACT_VERSIONS_CONTENT_TYPE_CD CHECK (CNTNT_TP_CD IN ('TEXT', 'MARKDOWN', 'XML', 'JAVA', 'JSON', 'SQL', 'YAML')),
    CONSTRAINT FK_ARTIFACT_VERSIONS_ARTIFACT FOREIGN KEY (ARTF_ID) REFERENCES dbo.ARTIFACTS(ARTF_ID),
    CONSTRAINT FK_ARTIFACT_VERSIONS_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID),
    CONSTRAINT FK_ARTIFACT_VERSIONS_ANALYSIS FOREIGN KEY (ANLS_ID) REFERENCES dbo.ANALYSIS_RESULTS(ANLS_ID),
    CONSTRAINT FK_ARTIFACT_VERSIONS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

ALTER TABLE dbo.ARTIFACTS
ADD CONSTRAINT FK_ARTIFACTS_CURRENT_VERSION FOREIGN KEY (CUR_ARTF_VER_ID) REFERENCES dbo.ARTIFACT_VERSIONS(ARTF_VER_ID);
GO

CREATE TABLE dbo.ARTIFACT_VALIDATION_REPORTS (
    VLDT_RSLT_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ARTF_VER_ID UNIQUEIDENTIFIER NOT NULL,
    VLDT_PRFL_NM NVARCHAR(150) NULL,
    VLDT_RSLT_CD NVARCHAR(10) NOT NULL,
    RSLT_JSON NVARCHAR(MAX) NOT NULL,
    MISSING_EVDC_JSON NVARCHAR(MAX) NULL,
    MANUAL_RVWR_POINTS_JSON NVARCHAR(MAX) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_ARTIFACT_VALIDATION_REPORTS PRIMARY KEY CLUSTERED (VLDT_RSLT_ID),
    CONSTRAINT CHK_ARTIFACT_VALIDATION_REPORTS_PASS_FAIL_CD CHECK (VLDT_RSLT_CD IN ('PASS', 'FAIL')),
    CONSTRAINT FK_ARTIFACT_VALIDATION_REPORTS_ARTIFACT_VERSION FOREIGN KEY (ARTF_VER_ID) REFERENCES dbo.ARTIFACT_VERSIONS(ARTF_VER_ID),
    CONSTRAINT FK_ARTIFACT_VALIDATION_REPORTS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TABLE dbo.ARTIFACT_APPROVAL_RECORDS (
    APRV_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ARTF_VER_ID UNIQUEIDENTIFIER NOT NULL,
    RVWR_USR_ID UNIQUEIDENTIFIER NOT NULL,
    DCISN_CD NVARCHAR(20) NOT NULL,
    RVWR_CNTNT NVARCHAR(MAX) NULL,
    CHKLST_RSLT_JSON NVARCHAR(MAX) NULL,
    APRV_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACT_APPROVAL_RECORDS PRIMARY KEY CLUSTERED (APRV_ID),
    CONSTRAINT CHK_ARTIFACT_APPROVAL_RECORDS_DECISION_CD CHECK (DCISN_CD IN ('APPROVED', 'REJECTED')),
    CONSTRAINT FK_ARTIFACT_APPROVAL_RECORDS_ARTIFACT_VERSION FOREIGN KEY (ARTF_VER_ID) REFERENCES dbo.ARTIFACT_VERSIONS(ARTF_VER_ID),
    CONSTRAINT FK_ARTIFACT_APPROVAL_RECORDS_REVIEWER FOREIGN KEY (RVWR_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   audit
   ========================= */
CREATE TABLE dbo.AUDIT_EVENTS (
    AUDT_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ACTR_USR_ID UNIQUEIDENTIFIER NULL,
    ACTION_CD NVARCHAR(100) NOT NULL,
    TRGT_TP_CD NVARCHAR(50) NOT NULL,
    TRGT_REF_ID NVARCHAR(100) NOT NULL,
    TRC_ID NVARCHAR(100) NULL,
    PAYLD_JSON NVARCHAR(MAX) NULL,
    AUDT_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUDIT_EVENTS PRIMARY KEY CLUSTERED (AUDT_ID),
    CONSTRAINT FK_AUDIT_EVENTS_ACTOR FOREIGN KEY (ACTR_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   Seed roles
   ========================= */
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE AUTH_GRP_NM = 'USER')
    INSERT INTO dbo.AUTH_ROLES(AUTH_GRP_NM, AUTH_GRP_DESC) VALUES ('USER', '일반 사용자');
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE AUTH_GRP_NM = 'REVIEWER')
    INSERT INTO dbo.AUTH_ROLES(AUTH_GRP_NM, AUTH_GRP_DESC) VALUES ('REVIEWER', '검토/승인 담당');
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE AUTH_GRP_NM = 'ADMIN')
    INSERT INTO dbo.AUTH_ROLES(AUTH_GRP_NM, AUTH_GRP_DESC) VALUES ('ADMIN', '운영/정책/프로필 관리자');
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE AUTH_GRP_NM = 'AUDITOR')
    INSERT INTO dbo.AUTH_ROLES(AUTH_GRP_NM, AUTH_GRP_DESC) VALUES ('AUDITOR', '감사로그 열람 담당');
GO

/* =========================
   Recommended indexes
   ========================= */
CREATE INDEX IX_CORE_WORK_REQUESTS_TYPE_STATUS_SUBMITTED_AT
    ON dbo.CORE_WORK_REQUESTS(REQ_TP_CD, CUR_STAT_CD, SUBMITTED_DTM DESC);
GO

CREATE INDEX IX_CORE_JOBS_REQUEST_STATUS
    ON dbo.CORE_JOBS(REQ_ID, CUR_STAT_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_CORE_JOB_STEPS_JOB_STEP_TYPE
    ON dbo.CORE_JOB_STEPS(JOB_ID, STEP_TP_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_REGISTRY_VERSIONS_ITEM_PUBLISHED
    ON dbo.REGISTRY_VERSIONS(RGST_ITEM_ID, PBLC_YN, VER_SEQ_NO DESC);
GO

CREATE INDEX IX_METADATA_SNAPSHOTS_PROFILE_CAPTURED
    ON dbo.METADATA_SNAPSHOTS(DB_PRFL_ID, CAPTURED_DTM DESC);
GO

CREATE INDEX IX_METADATA_OBJECT_CACHE_SNAPSHOT_TYPE_NAME
    ON dbo.METADATA_OBJECT_CACHE(SNAP_ID, OBJ_TP_CD, SCHM_NM, OBJ_NM);
GO

CREATE INDEX IX_METADATA_DEPENDENCY_EDGES_SNAPSHOT_FROM
    ON dbo.METADATA_DEPENDENCY_EDGES(SNAP_ID, FR_SCHM_NM, FR_OBJ_NM, DEPD_TP_CD);
GO

CREATE INDEX IX_METADATA_DEPENDENCY_EDGES_SNAPSHOT_TO
    ON dbo.METADATA_DEPENDENCY_EDGES(SNAP_ID, TO_SCHM_NM, TO_OBJ_NM, DEPD_TP_CD);
GO

CREATE INDEX IX_ANALYSIS_RESULTS_JOB_TARGET
    ON dbo.ANALYSIS_RESULTS(JOB_ID, TRGT_SCHM_NM, TRGT_OBJ_NM, CRE_DTM DESC);
GO

CREATE INDEX IX_ARTIFACTS_JOB_TYPE_STATUS
    ON dbo.ARTIFACTS(JOB_ID, ARTF_TP_CD, CUR_STAT_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_ARTIFACT_VERSIONS_ARTIFACT_VERSION_NO
    ON dbo.ARTIFACT_VERSIONS(ARTF_ID, VER_SEQ_NO DESC);
GO

CREATE INDEX IX_ARTIFACT_VALIDATION_REPORTS_ARTIFACT_VERSION
    ON dbo.ARTIFACT_VALIDATION_REPORTS(ARTF_VER_ID, CRE_DTM DESC);
GO

CREATE INDEX IX_ARTIFACT_APPROVAL_RECORDS_ARTIFACT_VERSION
    ON dbo.ARTIFACT_APPROVAL_RECORDS(ARTF_VER_ID, APRV_DTM DESC);
GO

CREATE INDEX IX_AUDIT_EVENTS_OCCURRED_AT
    ON dbo.AUDIT_EVENTS(AUDT_DTM DESC);
GO

CREATE INDEX IX_AUDIT_EVENTS_ACTOR_ACTION
    ON dbo.AUDIT_EVENTS(ACTR_USR_ID, ACTION_CD, AUDT_DTM DESC);
GO
