/*
  MSSQL Analysis Agent Platform
  Platform DB DDL Draft v5: Versioned Knowledge Assets / Fact Graph / Export

  Manual apply only. Codex must not execute this file automatically.
  This schema stores sanitized knowledge facts only. Raw SP definitions, raw SQL text,
  row data, secrets, raw prompts, and raw provider responses are intentionally absent.
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE dbo.KNOWLEDGE_ASSETS (
    ASST_ID NVARCHAR(80) NOT NULL,
    ASST_KIND_CD NVARCHAR(40) NOT NULL,
    DB_PRFL_REF_TXT NVARCHAR(150) NOT NULL,
    TRGT_TP_CD NVARCHAR(40) NOT NULL,
    TRGT_SCHM_NM NVARCHAR(128) NOT NULL DEFAULT '',
    TRGT_OBJ_NM NVARCHAR(128) NOT NULL,
    LOGICAL_KEY_TXT NVARCHAR(600) NOT NULL,
    CUR_VER_ID NVARCHAR(80) NULL,
    CUR_VER_NO INT NOT NULL DEFAULT 0,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NULL,
    SRC_JOB_ID NVARCHAR(80) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_ASSETS PRIMARY KEY CLUSTERED (ASST_ID),
    CONSTRAINT UQ_KNOWLEDGE_ASSETS_LOGICAL_KEY UNIQUE (LOGICAL_KEY_TXT),
    CONSTRAINT CHK_KNOWLEDGE_ASSETS_KIND CHECK (
        ASST_KIND_CD IN (
            'SP_ANALYSIS',
            'DEPENDENCY_EVIDENCE',
            'METADATA_PROFILE',
            'DTO_READINESS',
            'CANONICAL_ANALYSIS'
        )
    )
);
GO

CREATE TABLE dbo.KNOWLEDGE_ASSET_VERSIONS (
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    VER_SEQ_NO INT NOT NULL,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    SRC_JOB_ID NVARCHAR(80) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_ASSET_VERSIONS PRIMARY KEY CLUSTERED (ASST_VER_ID),
    CONSTRAINT UQ_KNOWLEDGE_ASSET_VERSIONS UNIQUE (ASST_ID, VER_SEQ_NO),
    CONSTRAINT UQ_KNOWLEDGE_ASSET_VERSIONS_HASH UNIQUE (ASST_ID, CNTNT_HASH_SHA256_VAL),
    CONSTRAINT FK_KNOWLEDGE_ASSET_VERSIONS_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID)
);
GO

ALTER TABLE dbo.KNOWLEDGE_ASSETS
ADD CONSTRAINT FK_KNOWLEDGE_ASSETS_CURRENT_VERSION FOREIGN KEY (CUR_VER_ID)
    REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID);
GO

CREATE TABLE dbo.KNOWLEDGE_FACTS (
    FACT_ID NVARCHAR(220) NOT NULL,
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    FACT_TP_CD NVARCHAR(80) NOT NULL,
    OBJ_REF_TXT NVARCHAR(500) NOT NULL,
    SMRY_TXT NVARCHAR(1000) NOT NULL,
    STAT_CD NVARCHAR(30) NOT NULL,
    EVDC_REFS_JSON NVARCHAR(MAX) NOT NULL,
    PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_FACTS PRIMARY KEY CLUSTERED (ASST_VER_ID, FACT_ID),
    CONSTRAINT CHK_KNOWLEDGE_FACTS_STATUS CHECK (
        STAT_CD IN ('OBSERVED', 'INFERRED_DESCRIPTION', 'REVIEW_REQUIRED')
    ),
    CONSTRAINT FK_KNOWLEDGE_FACTS_VERSION FOREIGN KEY (ASST_VER_ID)
        REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID),
    CONSTRAINT FK_KNOWLEDGE_FACTS_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID)
);
GO

CREATE TABLE dbo.KNOWLEDGE_FACT_EDGES (
    EDGE_ID NVARCHAR(220) NOT NULL,
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    FROM_FACT_ID NVARCHAR(220) NOT NULL,
    TO_FACT_ID NVARCHAR(220) NOT NULL,
    EDGE_TP_CD NVARCHAR(40) NOT NULL,
    EVDC_REFS_JSON NVARCHAR(MAX) NOT NULL,
    PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_FACT_EDGES PRIMARY KEY CLUSTERED (ASST_VER_ID, EDGE_ID),
    CONSTRAINT CHK_KNOWLEDGE_FACT_EDGES_TYPE CHECK (
        EDGE_TP_CD IN (
            'DEPENDS_ON',
            'DERIVED_FROM',
            'SUPPORTS',
            'READS',
            'WRITES',
            'CALLS',
            'FK_TO',
            'DTO_FIELD_OF'
        )
    ),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_VERSION FOREIGN KEY (ASST_VER_ID)
        REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_FROM_FACT FOREIGN KEY (ASST_VER_ID, FROM_FACT_ID)
        REFERENCES dbo.KNOWLEDGE_FACTS(ASST_VER_ID, FACT_ID),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_TO_FACT FOREIGN KEY (ASST_VER_ID, TO_FACT_ID)
        REFERENCES dbo.KNOWLEDGE_FACTS(ASST_VER_ID, FACT_ID)
);
GO

CREATE TABLE dbo.KNOWLEDGE_ASSET_JOB_LINKS (
    JOB_REF_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    LINK_TP_CD NVARCHAR(30) NOT NULL DEFAULT 'SOURCE',
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_ASSET_JOB_LINKS PRIMARY KEY CLUSTERED (JOB_REF_ID, ASST_ID, ASST_VER_ID),
    CONSTRAINT CHK_KNOWLEDGE_ASSET_JOB_LINKS_TYPE CHECK (LINK_TP_CD IN ('SOURCE')),
    CONSTRAINT FK_KNOWLEDGE_ASSET_JOB_LINKS_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID),
    CONSTRAINT FK_KNOWLEDGE_ASSET_JOB_LINKS_VERSION FOREIGN KEY (ASST_VER_ID)
        REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID)
);
GO

CREATE TABLE dbo.KNOWLEDGE_EXPORTS (
    EXPRT_ID NVARCHAR(80) NOT NULL,
    FMT_CD NVARCHAR(30) NOT NULL,
    CNTNT_TP_TXT NVARCHAR(100) NOT NULL,
    CNTNT_TXT NVARCHAR(MAX) NOT NULL,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    ASST_IDS_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_EXPORTS PRIMARY KEY CLUSTERED (EXPRT_ID),
    CONSTRAINT CHK_KNOWLEDGE_EXPORTS_FORMAT CHECK (FMT_CD IN ('JSONL', 'GRAPH_JSON'))
);
GO

CREATE INDEX IX_KNOWLEDGE_ASSETS_JOB
    ON dbo.KNOWLEDGE_ASSETS(SRC_JOB_ID, UPD_DTM DESC);
GO

CREATE INDEX IX_KNOWLEDGE_ASSETS_TARGET
    ON dbo.KNOWLEDGE_ASSETS(DB_PRFL_REF_TXT, TRGT_TP_CD, TRGT_SCHM_NM, TRGT_OBJ_NM);
GO

CREATE INDEX IX_KNOWLEDGE_FACTS_OBJECT
    ON dbo.KNOWLEDGE_FACTS(OBJ_REF_TXT, FACT_TP_CD);
GO

CREATE INDEX IX_KNOWLEDGE_ASSET_JOB_LINKS_JOB
    ON dbo.KNOWLEDGE_ASSET_JOB_LINKS(JOB_REF_ID, CRE_DTM DESC);
GO

CREATE INDEX IX_KNOWLEDGE_EXPORTS_CREATED
    ON dbo.KNOWLEDGE_EXPORTS(CRE_DTM DESC);
GO
