/*
  MSSQL Analysis · Documentation · Conversion Code Generation Agent Platform
  Platform DB DDL Draft v2 (SQL Server / T-SQL 기준)

  주의:
  - 업로드 기준 문서에는 플랫폼 운영 DBMS가 명시되어 있지 않다.
  - 아래 DDL은 실행 가능성을 높이기 위해 SQL Server(T-SQL) 기준으로 제시한 권장 초안이다.
  - 대용량 본문(content, analysis_json, payload_json 등)은 Object Storage 분리 저장을 전제로 content_ref를 함께 둔다.
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* =========================
   auth
   ========================= */
CREATE TABLE dbo.AUTH_USERS (
    user_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    login_id NVARCHAR(100) NOT NULL,
    display_name NVARCHAR(200) NOT NULL,
    email NVARCHAR(320) NULL,
    status_cd NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUTH_USERS PRIMARY KEY CLUSTERED (user_id),
    CONSTRAINT UQ_AUTH_USERS_LOGIN_ID UNIQUE (login_id),
    CONSTRAINT CHK_AUTH_USERS_STATUS_CD CHECK (status_cd IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);
GO

CREATE TABLE dbo.AUTH_ROLES (
    role_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    role_name NVARCHAR(100) NOT NULL,
    role_desc NVARCHAR(500) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUTH_ROLES PRIMARY KEY CLUSTERED (role_id),
    CONSTRAINT UQ_AUTH_ROLES_ROLE_NAME UNIQUE (role_name)
);
GO

CREATE TABLE dbo.AUTH_USER_ROLES (
    user_role_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    user_id UNIQUEIDENTIFIER NOT NULL,
    role_id UNIQUEIDENTIFIER NOT NULL,
    granted_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    granted_by UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_AUTH_USER_ROLES PRIMARY KEY CLUSTERED (user_role_id),
    CONSTRAINT UQ_AUTH_USER_ROLES UNIQUE (user_id, role_id),
    CONSTRAINT FK_AUTH_USER_ROLES_USER FOREIGN KEY (user_id) REFERENCES dbo.AUTH_USERS(user_id),
    CONSTRAINT FK_AUTH_USER_ROLES_ROLE FOREIGN KEY (role_id) REFERENCES dbo.AUTH_ROLES(role_id),
    CONSTRAINT FK_AUTH_USER_ROLES_GRANTED_BY FOREIGN KEY (granted_by) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

/* =========================
   core
   ========================= */
CREATE TABLE dbo.CORE_DB_PROFILES (
    db_profile_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    profile_name NVARCHAR(150) NOT NULL,
    db_type_cd NVARCHAR(30) NOT NULL DEFAULT 'MSSQL',
    host_name NVARCHAR(255) NOT NULL,
    port_no INT NOT NULL,
    database_name NVARCHAR(255) NOT NULL,
    connection_meta_json NVARCHAR(MAX) NULL,
    secret_ref NVARCHAR(255) NULL,
    read_only_yn CHAR(1) NOT NULL DEFAULT 'Y',
    status_cd NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by UNIQUEIDENTIFIER NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_by UNIQUEIDENTIFIER NULL,
    updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_DB_PROFILES PRIMARY KEY CLUSTERED (db_profile_id),
    CONSTRAINT UQ_CORE_DB_PROFILES_PROFILE_NAME UNIQUE (profile_name),
    CONSTRAINT CHK_CORE_DB_PROFILES_DB_TYPE_CD CHECK (db_type_cd IN ('MSSQL')),
    CONSTRAINT CHK_CORE_DB_PROFILES_READ_ONLY_YN CHECK (read_only_yn IN ('Y')),
    CONSTRAINT CHK_CORE_DB_PROFILES_STATUS_CD CHECK (status_cd IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT FK_CORE_DB_PROFILES_CREATED_BY FOREIGN KEY (created_by) REFERENCES dbo.AUTH_USERS(user_id),
    CONSTRAINT FK_CORE_DB_PROFILES_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

CREATE TABLE dbo.CORE_DB_PROFILE_ALLOWED_SCHEMAS (
    db_profile_allowed_schema_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    db_profile_id UNIQUEIDENTIFIER NOT NULL,
    schema_name NVARCHAR(128) NOT NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_DB_PROFILE_ALLOWED_SCHEMAS PRIMARY KEY CLUSTERED (db_profile_allowed_schema_id),
    CONSTRAINT UQ_CORE_DB_PROFILE_ALLOWED_SCHEMAS UNIQUE (db_profile_id, schema_name),
    CONSTRAINT FK_CORE_DB_PROFILE_ALLOWED_SCHEMAS_PROFILE FOREIGN KEY (db_profile_id) REFERENCES dbo.CORE_DB_PROFILES(db_profile_id)
);
GO

CREATE TABLE dbo.CORE_WORK_REQUESTS (
    request_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    request_type_cd NVARCHAR(30) NOT NULL,
    requester_id UNIQUEIDENTIFIER NOT NULL,
    reviewer_group_nm NVARCHAR(100) NULL,
    db_profile_id UNIQUEIDENTIFIER NOT NULL,
    target_payload_json NVARCHAR(MAX) NOT NULL,
    desired_outputs_json NVARCHAR(MAX) NULL,
    option_payload_json NVARCHAR(MAX) NULL,
    current_status_cd NVARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    trace_id NVARCHAR(100) NULL,
    submitted_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_WORK_REQUESTS PRIMARY KEY CLUSTERED (request_id),
    CONSTRAINT CHK_CORE_WORK_REQUESTS_REQUEST_TYPE_CD CHECK (request_type_cd IN ('SP_ANALYSIS', 'SCHEMA_SEARCH', 'CODE_GENERATION')),
    CONSTRAINT CHK_CORE_WORK_REQUESTS_CURRENT_STATUS_CD CHECK (current_status_cd IN ('SUBMITTED', 'COLLECTING_METADATA', 'ANALYZING', 'GENERATING', 'VALIDATING', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', 'CANCELED')),
    CONSTRAINT FK_CORE_WORK_REQUESTS_REQUESTER FOREIGN KEY (requester_id) REFERENCES dbo.AUTH_USERS(user_id),
    CONSTRAINT FK_CORE_WORK_REQUESTS_DB_PROFILE FOREIGN KEY (db_profile_id) REFERENCES dbo.CORE_DB_PROFILES(db_profile_id)
);
GO

CREATE TABLE dbo.CORE_JOBS (
    job_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    request_id UNIQUEIDENTIFIER NOT NULL,
    current_status_cd NVARCHAR(30) NOT NULL,
    started_at DATETIME2(3) NULL,
    ended_at DATETIME2(3) NULL,
    current_step_type_cd NVARCHAR(30) NULL,
    snapshot_id UNIQUEIDENTIFIER NULL,
    registry_binding_json NVARCHAR(MAX) NULL,
    worker_ref NVARCHAR(200) NULL,
    error_code NVARCHAR(100) NULL,
    error_message NVARCHAR(2000) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_JOBS PRIMARY KEY CLUSTERED (job_id),
    CONSTRAINT CHK_CORE_JOBS_CURRENT_STATUS_CD CHECK (current_status_cd IN ('SUBMITTED', 'COLLECTING_METADATA', 'ANALYZING', 'GENERATING', 'VALIDATING', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', 'CANCELED')),
    CONSTRAINT CHK_CORE_JOBS_CURRENT_STEP_TYPE_CD CHECK (current_step_type_cd IS NULL OR current_step_type_cd IN ('COLLECT_METADATA', 'ANALYZE', 'GENERATE', 'VALIDATE', 'REVIEW', 'PUBLISH')),
    CONSTRAINT FK_CORE_JOBS_REQUEST FOREIGN KEY (request_id) REFERENCES dbo.CORE_WORK_REQUESTS(request_id)
);
GO

CREATE TABLE dbo.CORE_JOB_STEPS (
    step_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    job_id UNIQUEIDENTIFIER NOT NULL,
    step_type_cd NVARCHAR(30) NOT NULL,
    status_cd NVARCHAR(20) NOT NULL,
    started_at DATETIME2(3) NULL,
    ended_at DATETIME2(3) NULL,
    retry_count INT NOT NULL DEFAULT 0,
    detail_json NVARCHAR(MAX) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_JOB_STEPS PRIMARY KEY CLUSTERED (step_id),
    CONSTRAINT CHK_CORE_JOB_STEPS_STEP_TYPE_CD CHECK (step_type_cd IN ('COLLECT_METADATA', 'ANALYZE', 'GENERATE', 'VALIDATE', 'REVIEW', 'PUBLISH')),
    CONSTRAINT CHK_CORE_JOB_STEPS_STATUS_CD CHECK (status_cd IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT FK_CORE_JOB_STEPS_JOB FOREIGN KEY (job_id) REFERENCES dbo.CORE_JOBS(job_id)
);
GO

/* =========================
   registry
   ========================= */
CREATE TABLE dbo.REGISTRY_ITEMS (
    registry_item_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    kind_cd NVARCHAR(30) NOT NULL,
    item_name NVARCHAR(150) NOT NULL,
    item_desc NVARCHAR(1000) NULL,
    created_by UNIQUEIDENTIFIER NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_REGISTRY_ITEMS PRIMARY KEY CLUSTERED (registry_item_id),
    CONSTRAINT UQ_REGISTRY_ITEMS UNIQUE (kind_cd, item_name),
    CONSTRAINT CHK_REGISTRY_ITEMS_KIND_CD CHECK (kind_cd IN ('PROMPT', 'TEMPLATE', 'MODEL_POLICY', 'DB_PROFILE_POLICY')),
    CONSTRAINT FK_REGISTRY_ITEMS_CREATED_BY FOREIGN KEY (created_by) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

CREATE TABLE dbo.REGISTRY_VERSIONS (
    version_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    registry_item_id UNIQUEIDENTIFIER NOT NULL,
    version_no INT NOT NULL,
    content_type_cd NVARCHAR(20) NOT NULL,
    content_ref NVARCHAR(500) NULL,
    content_text NVARCHAR(MAX) NULL,
    checksum_sha256 NVARCHAR(64) NULL,
    published_yn CHAR(1) NOT NULL DEFAULT 'N',
    created_by UNIQUEIDENTIFIER NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    published_at DATETIME2(3) NULL,
    published_by UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_REGISTRY_VERSIONS PRIMARY KEY CLUSTERED (version_id),
    CONSTRAINT UQ_REGISTRY_VERSIONS UNIQUE (registry_item_id, version_no),
    CONSTRAINT CHK_REGISTRY_VERSIONS_CONTENT_TYPE_CD CHECK (content_type_cd IN ('TEXT', 'YAML', 'JSON', 'MARKDOWN')),
    CONSTRAINT CHK_REGISTRY_VERSIONS_PUBLISHED_YN CHECK (published_yn IN ('Y', 'N')),
    CONSTRAINT FK_REGISTRY_VERSIONS_ITEM FOREIGN KEY (registry_item_id) REFERENCES dbo.REGISTRY_ITEMS(registry_item_id),
    CONSTRAINT FK_REGISTRY_VERSIONS_CREATED_BY FOREIGN KEY (created_by) REFERENCES dbo.AUTH_USERS(user_id),
    CONSTRAINT FK_REGISTRY_VERSIONS_PUBLISHED_BY FOREIGN KEY (published_by) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

/* =========================
   metadata
   ========================= */
CREATE TABLE dbo.METADATA_SNAPSHOTS (
    snapshot_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    db_profile_id UNIQUEIDENTIFIER NOT NULL,
    snapshot_scope_cd NVARCHAR(30) NOT NULL,
    object_scope_json NVARCHAR(MAX) NULL,
    source_hash NVARCHAR(128) NULL,
    captured_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    captured_by_job_id UNIQUEIDENTIFIER NULL,
    notes NVARCHAR(1000) NULL,
    CONSTRAINT PK_METADATA_SNAPSHOTS PRIMARY KEY CLUSTERED (snapshot_id),
    CONSTRAINT CHK_METADATA_SNAPSHOTS_SCOPE_CD CHECK (snapshot_scope_cd IN ('LATEST', 'PINNED', 'JOB_BOUND')),
    CONSTRAINT FK_METADATA_SNAPSHOTS_PROFILE FOREIGN KEY (db_profile_id) REFERENCES dbo.CORE_DB_PROFILES(db_profile_id),
    CONSTRAINT FK_METADATA_SNAPSHOTS_JOB FOREIGN KEY (captured_by_job_id) REFERENCES dbo.CORE_JOBS(job_id)
);
GO

CREATE TABLE dbo.METADATA_OBJECT_CACHE (
    object_cache_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    snapshot_id UNIQUEIDENTIFIER NOT NULL,
    object_type_cd NVARCHAR(30) NOT NULL,
    schema_name NVARCHAR(128) NOT NULL,
    object_name NVARCHAR(128) NOT NULL,
    logical_name NVARCHAR(255) NULL,
    description_txt NVARCHAR(MAX) NULL,
    normalized_terms NVARCHAR(MAX) NULL,
    metadata_json NVARCHAR(MAX) NOT NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_OBJECT_CACHE PRIMARY KEY CLUSTERED (object_cache_id),
    CONSTRAINT UQ_METADATA_OBJECT_CACHE UNIQUE (snapshot_id, object_type_cd, schema_name, object_name),
    CONSTRAINT CHK_METADATA_OBJECT_CACHE_OBJECT_TYPE_CD CHECK (object_type_cd IN ('PROCEDURE', 'TABLE', 'COLUMN', 'INDEX', 'PK', 'FK', 'FUNCTION', 'VIEW', 'EXTENDED_PROPERTY')),
    CONSTRAINT FK_METADATA_OBJECT_CACHE_SNAPSHOT FOREIGN KEY (snapshot_id) REFERENCES dbo.METADATA_SNAPSHOTS(snapshot_id)
);
GO

CREATE TABLE dbo.METADATA_DEPENDENCY_EDGES (
    dependency_edge_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    snapshot_id UNIQUEIDENTIFIER NOT NULL,
    from_object_type_cd NVARCHAR(30) NOT NULL,
    from_schema_name NVARCHAR(128) NOT NULL,
    from_object_name NVARCHAR(128) NOT NULL,
    relation_type_cd NVARCHAR(30) NOT NULL,
    to_object_type_cd NVARCHAR(30) NOT NULL,
    to_schema_name NVARCHAR(128) NOT NULL,
    to_object_name NVARCHAR(128) NOT NULL,
    evidence_json NVARCHAR(MAX) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_DEPENDENCY_EDGES PRIMARY KEY CLUSTERED (dependency_edge_id),
    CONSTRAINT CHK_METADATA_DEPENDENCY_EDGES_RELATION_TYPE_CD CHECK (relation_type_cd IN ('READS', 'WRITES', 'CALLS', 'REFERENCES', 'USES_TEMP_TABLE', 'USES_DYNAMIC_SQL')),
    CONSTRAINT FK_METADATA_DEPENDENCY_EDGES_SNAPSHOT FOREIGN KEY (snapshot_id) REFERENCES dbo.METADATA_SNAPSHOTS(snapshot_id)
);
GO

/* =========================
   analysis
   ========================= */
CREATE TABLE dbo.ANALYSIS_RESULTS (
    analysis_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    job_id UNIQUEIDENTIFIER NOT NULL,
    snapshot_id UNIQUEIDENTIFIER NOT NULL,
    target_type_cd NVARCHAR(30) NOT NULL,
    target_schema_name NVARCHAR(128) NOT NULL,
    target_object_name NVARCHAR(128) NOT NULL,
    analysis_status_cd NVARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    analysis_json NVARCHAR(MAX) NOT NULL,
    analysis_summary NVARCHAR(2000) NULL,
    confidence_cd NVARCHAR(20) NULL,
    content_ref NVARCHAR(500) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ANALYSIS_RESULTS PRIMARY KEY CLUSTERED (analysis_id),
    CONSTRAINT CHK_ANALYSIS_RESULTS_TARGET_TYPE_CD CHECK (target_type_cd IN ('PROCEDURE', 'TABLE', 'VIEW', 'FUNCTION')),
    CONSTRAINT CHK_ANALYSIS_RESULTS_STATUS_CD CHECK (analysis_status_cd IN ('COMPLETED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT CHK_ANALYSIS_RESULTS_CONFIDENCE_CD CHECK (confidence_cd IS NULL OR confidence_cd IN ('DETERMINISTIC', 'INFERRED', 'REVIEW_REQUIRED')),
    CONSTRAINT FK_ANALYSIS_RESULTS_JOB FOREIGN KEY (job_id) REFERENCES dbo.CORE_JOBS(job_id),
    CONSTRAINT FK_ANALYSIS_RESULTS_SNAPSHOT FOREIGN KEY (snapshot_id) REFERENCES dbo.METADATA_SNAPSHOTS(snapshot_id)
);
GO

CREATE TABLE dbo.ANALYSIS_EVIDENCE_REFS (
    analysis_evidence_ref_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    analysis_id UNIQUEIDENTIFIER NOT NULL,
    evidence_type_cd NVARCHAR(30) NOT NULL,
    object_ref NVARCHAR(500) NOT NULL,
    locator_txt NVARCHAR(1000) NULL,
    confidence_cd NVARCHAR(20) NOT NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ANALYSIS_EVIDENCE_REFS PRIMARY KEY CLUSTERED (analysis_evidence_ref_id),
    CONSTRAINT CHK_ANALYSIS_EVIDENCE_REFS_EVIDENCE_TYPE_CD CHECK (evidence_type_cd IN ('OBJECT', 'COLUMN', 'INDEX', 'CONSTRAINT', 'DEFINITION', 'SNAPSHOT')),
    CONSTRAINT CHK_ANALYSIS_EVIDENCE_REFS_CONFIDENCE_CD CHECK (confidence_cd IN ('DETERMINISTIC', 'INFERRED', 'REVIEW_REQUIRED')),
    CONSTRAINT FK_ANALYSIS_EVIDENCE_REFS_ANALYSIS FOREIGN KEY (analysis_id) REFERENCES dbo.ANALYSIS_RESULTS(analysis_id)
);
GO

/* =========================
   artifact
   ========================= */
CREATE TABLE dbo.ARTIFACTS (
    artifact_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    job_id UNIQUEIDENTIFIER NOT NULL,
    artifact_type_cd NVARCHAR(40) NOT NULL,
    current_status_cd NVARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    current_version_id UNIQUEIDENTIFIER NULL,
    title NVARCHAR(300) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACTS PRIMARY KEY CLUSTERED (artifact_id),
    CONSTRAINT CHK_ARTIFACTS_TYPE_CD CHECK (artifact_type_cd IN ('SP_ANALYSIS_DOC', 'DEPENDENCY_REPORT', 'METADATA_QUERY_RESULT', 'SCHEMA_ENRICHMENT_RESULT', 'MAPPER_XML', 'MAPPER_INTERFACE', 'SERVICE_DRAFT', 'DTO_DRAFT', 'VO_DRAFT', 'MODEL_DRAFT', 'DDL_DRAFT', 'VALIDATION_REPORT', 'APPROVAL_LOG')),
    CONSTRAINT CHK_ARTIFACTS_STATUS_CD CHECK (current_status_cd IN ('DRAFT', 'VALIDATED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT FK_ARTIFACTS_JOB FOREIGN KEY (job_id) REFERENCES dbo.CORE_JOBS(job_id)
);
GO

CREATE TABLE dbo.ARTIFACT_VERSIONS (
    artifact_version_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    artifact_id UNIQUEIDENTIFIER NOT NULL,
    version_no INT NOT NULL,
    content_type_cd NVARCHAR(20) NOT NULL,
    content_ref NVARCHAR(500) NULL,
    content_text NVARCHAR(MAX) NULL,
    checksum_sha256 NVARCHAR(64) NULL,
    snapshot_id UNIQUEIDENTIFIER NULL,
    analysis_id UNIQUEIDENTIFIER NULL,
    registry_binding_json NVARCHAR(MAX) NULL,
    evidence_json NVARCHAR(MAX) NULL,
    created_by UNIQUEIDENTIFIER NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACT_VERSIONS PRIMARY KEY CLUSTERED (artifact_version_id),
    CONSTRAINT UQ_ARTIFACT_VERSIONS UNIQUE (artifact_id, version_no),
    CONSTRAINT CHK_ARTIFACT_VERSIONS_CONTENT_TYPE_CD CHECK (content_type_cd IN ('TEXT', 'MARKDOWN', 'XML', 'JAVA', 'JSON', 'SQL', 'YAML')),
    CONSTRAINT FK_ARTIFACT_VERSIONS_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES dbo.ARTIFACTS(artifact_id),
    CONSTRAINT FK_ARTIFACT_VERSIONS_SNAPSHOT FOREIGN KEY (snapshot_id) REFERENCES dbo.METADATA_SNAPSHOTS(snapshot_id),
    CONSTRAINT FK_ARTIFACT_VERSIONS_ANALYSIS FOREIGN KEY (analysis_id) REFERENCES dbo.ANALYSIS_RESULTS(analysis_id),
    CONSTRAINT FK_ARTIFACT_VERSIONS_CREATED_BY FOREIGN KEY (created_by) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

ALTER TABLE dbo.ARTIFACTS
ADD CONSTRAINT FK_ARTIFACTS_CURRENT_VERSION FOREIGN KEY (current_version_id) REFERENCES dbo.ARTIFACT_VERSIONS(artifact_version_id);
GO

CREATE TABLE dbo.ARTIFACT_VALIDATION_REPORTS (
    report_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    artifact_version_id UNIQUEIDENTIFIER NOT NULL,
    validation_profile_nm NVARCHAR(150) NULL,
    pass_fail_cd NVARCHAR(10) NOT NULL,
    result_json NVARCHAR(MAX) NOT NULL,
    missing_evidence_json NVARCHAR(MAX) NULL,
    manual_review_points_json NVARCHAR(MAX) NULL,
    created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    created_by UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_ARTIFACT_VALIDATION_REPORTS PRIMARY KEY CLUSTERED (report_id),
    CONSTRAINT CHK_ARTIFACT_VALIDATION_REPORTS_PASS_FAIL_CD CHECK (pass_fail_cd IN ('PASS', 'FAIL')),
    CONSTRAINT FK_ARTIFACT_VALIDATION_REPORTS_ARTIFACT_VERSION FOREIGN KEY (artifact_version_id) REFERENCES dbo.ARTIFACT_VERSIONS(artifact_version_id),
    CONSTRAINT FK_ARTIFACT_VALIDATION_REPORTS_CREATED_BY FOREIGN KEY (created_by) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

CREATE TABLE dbo.ARTIFACT_APPROVAL_RECORDS (
    approval_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    artifact_version_id UNIQUEIDENTIFIER NOT NULL,
    reviewer_id UNIQUEIDENTIFIER NOT NULL,
    decision_cd NVARCHAR(20) NOT NULL,
    reviewer_comment NVARCHAR(MAX) NULL,
    checklist_result_json NVARCHAR(MAX) NULL,
    approved_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACT_APPROVAL_RECORDS PRIMARY KEY CLUSTERED (approval_id),
    CONSTRAINT CHK_ARTIFACT_APPROVAL_RECORDS_DECISION_CD CHECK (decision_cd IN ('APPROVED', 'REJECTED')),
    CONSTRAINT FK_ARTIFACT_APPROVAL_RECORDS_ARTIFACT_VERSION FOREIGN KEY (artifact_version_id) REFERENCES dbo.ARTIFACT_VERSIONS(artifact_version_id),
    CONSTRAINT FK_ARTIFACT_APPROVAL_RECORDS_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

/* =========================
   audit
   ========================= */
CREATE TABLE dbo.AUDIT_EVENTS (
    audit_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    actor_id UNIQUEIDENTIFIER NULL,
    action_cd NVARCHAR(100) NOT NULL,
    target_type_cd NVARCHAR(50) NOT NULL,
    target_id NVARCHAR(100) NOT NULL,
    trace_id NVARCHAR(100) NULL,
    payload_json NVARCHAR(MAX) NULL,
    occurred_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUDIT_EVENTS PRIMARY KEY CLUSTERED (audit_id),
    CONSTRAINT FK_AUDIT_EVENTS_ACTOR FOREIGN KEY (actor_id) REFERENCES dbo.AUTH_USERS(user_id)
);
GO

/* =========================
   Seed roles
   ========================= */
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE role_name = 'USER')
    INSERT INTO dbo.AUTH_ROLES(role_name, role_desc) VALUES ('USER', '일반 사용자');
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE role_name = 'REVIEWER')
    INSERT INTO dbo.AUTH_ROLES(role_name, role_desc) VALUES ('REVIEWER', '검토/승인 담당');
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE role_name = 'ADMIN')
    INSERT INTO dbo.AUTH_ROLES(role_name, role_desc) VALUES ('ADMIN', '운영/정책/프로필 관리자');
IF NOT EXISTS (SELECT 1 FROM dbo.AUTH_ROLES WHERE role_name = 'AUDITOR')
    INSERT INTO dbo.AUTH_ROLES(role_name, role_desc) VALUES ('AUDITOR', '감사로그 열람 담당');
GO

/* =========================
   Recommended indexes
   ========================= */
CREATE INDEX IX_CORE_WORK_REQUESTS_TYPE_STATUS_SUBMITTED_AT
    ON dbo.CORE_WORK_REQUESTS(request_type_cd, current_status_cd, submitted_at DESC);
GO

CREATE INDEX IX_CORE_JOBS_REQUEST_STATUS
    ON dbo.CORE_JOBS(request_id, current_status_cd, created_at DESC);
GO

CREATE INDEX IX_CORE_JOB_STEPS_JOB_STEP_TYPE
    ON dbo.CORE_JOB_STEPS(job_id, step_type_cd, created_at DESC);
GO

CREATE INDEX IX_REGISTRY_VERSIONS_ITEM_PUBLISHED
    ON dbo.REGISTRY_VERSIONS(registry_item_id, published_yn, version_no DESC);
GO

CREATE INDEX IX_METADATA_SNAPSHOTS_PROFILE_CAPTURED
    ON dbo.METADATA_SNAPSHOTS(db_profile_id, captured_at DESC);
GO

CREATE INDEX IX_METADATA_OBJECT_CACHE_SNAPSHOT_TYPE_NAME
    ON dbo.METADATA_OBJECT_CACHE(snapshot_id, object_type_cd, schema_name, object_name);
GO

CREATE INDEX IX_METADATA_DEPENDENCY_EDGES_SNAPSHOT_FROM
    ON dbo.METADATA_DEPENDENCY_EDGES(snapshot_id, from_schema_name, from_object_name, relation_type_cd);
GO

CREATE INDEX IX_METADATA_DEPENDENCY_EDGES_SNAPSHOT_TO
    ON dbo.METADATA_DEPENDENCY_EDGES(snapshot_id, to_schema_name, to_object_name, relation_type_cd);
GO

CREATE INDEX IX_ANALYSIS_RESULTS_JOB_TARGET
    ON dbo.ANALYSIS_RESULTS(job_id, target_schema_name, target_object_name, created_at DESC);
GO

CREATE INDEX IX_ARTIFACTS_JOB_TYPE_STATUS
    ON dbo.ARTIFACTS(job_id, artifact_type_cd, current_status_cd, created_at DESC);
GO

CREATE INDEX IX_ARTIFACT_VERSIONS_ARTIFACT_VERSION_NO
    ON dbo.ARTIFACT_VERSIONS(artifact_id, version_no DESC);
GO

CREATE INDEX IX_ARTIFACT_VALIDATION_REPORTS_ARTIFACT_VERSION
    ON dbo.ARTIFACT_VALIDATION_REPORTS(artifact_version_id, created_at DESC);
GO

CREATE INDEX IX_ARTIFACT_APPROVAL_RECORDS_ARTIFACT_VERSION
    ON dbo.ARTIFACT_APPROVAL_RECORDS(artifact_version_id, approved_at DESC);
GO

CREATE INDEX IX_AUDIT_EVENTS_OCCURRED_AT
    ON dbo.AUDIT_EVENTS(occurred_at DESC);
GO

CREATE INDEX IX_AUDIT_EVENTS_ACTOR_ACTION
    ON dbo.AUDIT_EVENTS(actor_id, action_cd, occurred_at DESC);
GO
