/*
  MSSQL Analysis Agent Platform
  Platform DB DDL Draft v11: PLF full fresh-create schema

  Manual apply only. Codex and the API must not execute this file automatically.
  This file targets a new, empty PLF database and consolidates the final schema
  state from v2, v3, v4, v6, v7, v8, v9, and v10. The v5 human-review knowledge
  draft is superseded by v6 and is intentionally absent.

  This schema stores platform workflow state and sanitized evidence only. It
  must not be treated as an automatic migration, source apply path, deployment
  gate, row-data access path, stored procedure run path, or secret store.
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* =========================
   auth
   ========================= */
CREATE TABLE dbo.AUTH_USERS (
    USR_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    LGN_ID NVARCHAR(100) NOT NULL,
    USR_NM NVARCHAR(200) NOT NULL,
    EML_ADR NVARCHAR(320) NULL,
    STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUTH_USERS PRIMARY KEY CLUSTERED (USR_ID),
    CONSTRAINT UQ_AUTH_USERS_LOGIN_ID UNIQUE (LGN_ID),
    CONSTRAINT CHK_AUTH_USERS_STATUS_CD CHECK (STAT_CD IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);
GO

CREATE TABLE dbo.AUTH_ROLES (
    AUTH_GRP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    AUTH_GRP_NM NVARCHAR(100) NOT NULL,
    AUTH_GRP_DESC NVARCHAR(500) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUTH_ROLES PRIMARY KEY CLUSTERED (AUTH_GRP_ID),
    CONSTRAINT UQ_AUTH_ROLES_ROLE_NAME UNIQUE (AUTH_GRP_NM)
);
GO

CREATE TABLE dbo.AUTH_USER_ROLES (
    USR_AUTH_GRP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    USR_ID UNIQUEIDENTIFIER NOT NULL,
    AUTH_GRP_ID UNIQUEIDENTIFIER NOT NULL,
    GRT_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    GRT_USR_ID UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_AUTH_USER_ROLES PRIMARY KEY CLUSTERED (USR_AUTH_GRP_ID),
    CONSTRAINT UQ_AUTH_USER_ROLES UNIQUE (USR_ID, AUTH_GRP_ID),
    CONSTRAINT FK_AUTH_USER_ROLES_USER FOREIGN KEY (USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_AUTH_USER_ROLES_ROLE FOREIGN KEY (AUTH_GRP_ID) REFERENCES dbo.AUTH_ROLES(AUTH_GRP_ID),
    CONSTRAINT FK_AUTH_USER_ROLES_GRANTED_BY FOREIGN KEY (GRT_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   core
   ========================= */
CREATE TABLE dbo.CORE_DB_PROFILES (
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    DB_PRFL_NM NVARCHAR(150) NOT NULL,
    DBMS_TP_CD NVARCHAR(30) NOT NULL DEFAULT 'MSSQL',
    HOST_NM NVARCHAR(255) NOT NULL,
    PORT_NO INT NOT NULL,
    DB_NM NVARCHAR(255) NOT NULL,
    CONNECTION_META_JSON NVARCHAR(MAX) NULL,
    SCRT_REF_ID NVARCHAR(255) NULL,
    READ_ONLY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_USR_ID UNIQUEIDENTIFIER NULL,
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_DB_PROFILES PRIMARY KEY CLUSTERED (DB_PRFL_ID),
    CONSTRAINT UQ_CORE_DB_PROFILES_PROFILE_NAME UNIQUE (DB_PRFL_NM),
    CONSTRAINT CHK_CORE_DB_PROFILES_DB_TYPE_CD CHECK (DBMS_TP_CD IN ('MSSQL')),
    CONSTRAINT CHK_CORE_DB_PROFILES_READ_ONLY_YN CHECK (READ_ONLY_YN IN ('Y')),
    CONSTRAINT CHK_CORE_DB_PROFILES_STATUS_CD CHECK (STAT_CD IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT FK_CORE_DB_PROFILES_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_CORE_DB_PROFILES_UPDATED_BY FOREIGN KEY (UPD_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TABLE dbo.CORE_DB_PROFILE_ALLOWED_SCHEMAS (
    DB_PRFL_SCHM_MAP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL,
    SCHM_NM NVARCHAR(128) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_DB_PROFILE_ALLOWED_SCHEMAS PRIMARY KEY CLUSTERED (DB_PRFL_SCHM_MAP_ID),
    CONSTRAINT UQ_CORE_DB_PROFILE_ALLOWED_SCHEMAS UNIQUE (DB_PRFL_ID, SCHM_NM),
    CONSTRAINT FK_CORE_DB_PROFILE_ALLOWED_SCHEMAS_PROFILE FOREIGN KEY (DB_PRFL_ID) REFERENCES dbo.CORE_DB_PROFILES(DB_PRFL_ID)
);
GO

CREATE TABLE dbo.CORE_WORK_REQUESTS (
    REQ_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    REQ_TP_CD NVARCHAR(30) NOT NULL,
    REQR_USR_ID UNIQUEIDENTIFIER NOT NULL,
    RVWR_GRP_NM NVARCHAR(100) NULL,
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL,
    TRGT_PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    DESIRED_RSLT_JSON NVARCHAR(MAX) NULL,
    OPTN_PAYLD_JSON NVARCHAR(MAX) NULL,
    CUR_STAT_CD NVARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    TRC_ID NVARCHAR(100) NULL,
    CANON_TRGT_KEY_TXT NVARCHAR(300) NULL,
    SUBMITTED_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_WORK_REQUESTS PRIMARY KEY CLUSTERED (REQ_ID),
    CONSTRAINT CHK_CORE_WORK_REQUESTS_REQUEST_TYPE_CD CHECK (REQ_TP_CD IN ('SP_ANALYSIS', 'SCHEMA_SEARCH', 'CODE_GENERATION')),
    CONSTRAINT CHK_CORE_WORK_REQUESTS_CURRENT_STATUS_CD CHECK (
        CUR_STAT_CD IN (
            'SUBMITTED',
            'COLLECTING_METADATA',
            'ANALYZING',
            'GENERATING',
            'VALIDATING',
            'VALIDATION_COMPLETE',
            'REVIEW_PENDING',
            'APPROVED',
            'REJECTED',
            'PUBLISHED',
            'FAILED',
            'CANCELED'
        )
    ),
    CONSTRAINT FK_CORE_WORK_REQUESTS_REQUESTER FOREIGN KEY (REQR_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_CORE_WORK_REQUESTS_DB_PROFILE FOREIGN KEY (DB_PRFL_ID) REFERENCES dbo.CORE_DB_PROFILES(DB_PRFL_ID)
);
GO

CREATE TABLE dbo.CORE_JOBS (
    JOB_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    REQ_ID UNIQUEIDENTIFIER NOT NULL,
    CUR_STAT_CD NVARCHAR(30) NOT NULL,
    START_DTM DATETIME2(3) NULL,
    END_DTM DATETIME2(3) NULL,
    CUR_STEP_TP_CD NVARCHAR(30) NULL,
    SNAP_ID UNIQUEIDENTIFIER NULL,
    CANON_TRGT_KEY_TXT NVARCHAR(300) NULL,
    RGST_BINDING_JSON NVARCHAR(MAX) NULL,
    WRKR_REF_ID NVARCHAR(200) NULL,
    ERR_CD NVARCHAR(100) NULL,
    ERR_CNTNT NVARCHAR(2000) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_JOBS PRIMARY KEY CLUSTERED (JOB_ID),
    CONSTRAINT CHK_CORE_JOBS_CURRENT_STATUS_CD CHECK (
        CUR_STAT_CD IN (
            'SUBMITTED',
            'COLLECTING_METADATA',
            'ANALYZING',
            'GENERATING',
            'VALIDATING',
            'VALIDATION_COMPLETE',
            'REVIEW_PENDING',
            'APPROVED',
            'REJECTED',
            'PUBLISHED',
            'FAILED',
            'CANCELED'
        )
    ),
    CONSTRAINT CHK_CORE_JOBS_CURRENT_STEP_TYPE_CD CHECK (CUR_STEP_TP_CD IS NULL OR CUR_STEP_TP_CD IN ('COLLECT_METADATA', 'ANALYZE', 'GENERATE', 'VALIDATE', 'REVIEW', 'PUBLISH')),
    CONSTRAINT FK_CORE_JOBS_REQUEST FOREIGN KEY (REQ_ID) REFERENCES dbo.CORE_WORK_REQUESTS(REQ_ID)
);
GO

CREATE TABLE dbo.CORE_JOB_STEPS (
    STEP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    STEP_TP_CD NVARCHAR(30) NOT NULL,
    STAT_CD NVARCHAR(20) NOT NULL,
    START_DTM DATETIME2(3) NULL,
    END_DTM DATETIME2(3) NULL,
    RETRY_CNT INT NOT NULL DEFAULT 0,
    STEP_JSON NVARCHAR(MAX) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CORE_JOB_STEPS PRIMARY KEY CLUSTERED (STEP_ID),
    CONSTRAINT CHK_CORE_JOB_STEPS_STEP_TYPE_CD CHECK (STEP_TP_CD IN ('COLLECT_METADATA', 'ANALYZE', 'GENERATE', 'VALIDATE', 'REVIEW', 'PUBLISH')),
    CONSTRAINT CHK_CORE_JOB_STEPS_STATUS_CD CHECK (STAT_CD IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT FK_CORE_JOB_STEPS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

/* =========================
   registry
   ========================= */
CREATE TABLE dbo.REGISTRY_ITEMS (
    RGST_ITEM_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ITEM_TP_CD NVARCHAR(30) NOT NULL,
    ITEM_NM NVARCHAR(150) NOT NULL,
    ITEM_DESC NVARCHAR(1000) NULL,
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_REGISTRY_ITEMS PRIMARY KEY CLUSTERED (RGST_ITEM_ID),
    CONSTRAINT UQ_REGISTRY_ITEMS UNIQUE (ITEM_TP_CD, ITEM_NM),
    CONSTRAINT CHK_REGISTRY_ITEMS_KIND_CD CHECK (ITEM_TP_CD IN ('PROMPT', 'TEMPLATE', 'MODEL_POLICY', 'DB_PROFILE_POLICY')),
    CONSTRAINT FK_REGISTRY_ITEMS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TABLE dbo.REGISTRY_VERSIONS (
    RGST_VER_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    RGST_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
    VER_SEQ_NO INT NOT NULL,
    CNTNT_TP_CD NVARCHAR(20) NOT NULL,
    CNTNT_REF_ID NVARCHAR(500) NULL,
    CNTNT_TXT NVARCHAR(MAX) NULL,
    CHK_SUM_SHA256_VAL NVARCHAR(64) NULL,
    PBLC_YN CHAR(1) NOT NULL DEFAULT 'N',
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    PBLC_DTM DATETIME2(3) NULL,
    PBLC_USR_ID UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_REGISTRY_VERSIONS PRIMARY KEY CLUSTERED (RGST_VER_ID),
    CONSTRAINT UQ_REGISTRY_VERSIONS UNIQUE (RGST_ITEM_ID, VER_SEQ_NO),
    CONSTRAINT CHK_REGISTRY_VERSIONS_CONTENT_TYPE_CD CHECK (CNTNT_TP_CD IN ('TEXT', 'YAML', 'JSON', 'MARKDOWN')),
    CONSTRAINT CHK_REGISTRY_VERSIONS_PUBLISHED_YN CHECK (PBLC_YN IN ('Y', 'N')),
    CONSTRAINT FK_REGISTRY_VERSIONS_ITEM FOREIGN KEY (RGST_ITEM_ID) REFERENCES dbo.REGISTRY_ITEMS(RGST_ITEM_ID),
    CONSTRAINT FK_REGISTRY_VERSIONS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID),
    CONSTRAINT FK_REGISTRY_VERSIONS_PUBLISHED_BY FOREIGN KEY (PBLC_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   metadata
   ========================= */
CREATE TABLE dbo.METADATA_SNAPSHOTS (
    SNAP_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    DB_PRFL_ID UNIQUEIDENTIFIER NOT NULL,
    SNAP_SCOPE_CD NVARCHAR(30) NOT NULL,
    OBJ_SCOPE_JSON NVARCHAR(MAX) NULL,
    SRC_HASH_VAL NVARCHAR(128) NULL,
    CAPTURED_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CAPTURED_JOB_ID UNIQUEIDENTIFIER NULL,
    REM_CNTNT NVARCHAR(1000) NULL,
    CONSTRAINT PK_METADATA_SNAPSHOTS PRIMARY KEY CLUSTERED (SNAP_ID),
    CONSTRAINT CHK_METADATA_SNAPSHOTS_SCOPE_CD CHECK (SNAP_SCOPE_CD IN ('LATEST', 'PINNED', 'JOB_BOUND')),
    CONSTRAINT FK_METADATA_SNAPSHOTS_PROFILE FOREIGN KEY (DB_PRFL_ID) REFERENCES dbo.CORE_DB_PROFILES(DB_PRFL_ID),
    CONSTRAINT FK_METADATA_SNAPSHOTS_JOB FOREIGN KEY (CAPTURED_JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

CREATE TABLE dbo.METADATA_OBJECT_CACHE (
    OBJ_CACHE_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    SNAP_ID UNIQUEIDENTIFIER NOT NULL,
    OBJ_TP_CD NVARCHAR(30) NOT NULL,
    SCHM_NM NVARCHAR(128) NOT NULL,
    OBJ_NM NVARCHAR(128) NOT NULL,
    LGC_NM NVARCHAR(255) NULL,
    OBJ_DESC NVARCHAR(MAX) NULL,
    NORMALIZED_TERMS_TXT NVARCHAR(MAX) NULL,
    META_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_OBJECT_CACHE PRIMARY KEY CLUSTERED (OBJ_CACHE_ID),
    CONSTRAINT UQ_METADATA_OBJECT_CACHE UNIQUE (SNAP_ID, OBJ_TP_CD, SCHM_NM, OBJ_NM),
    CONSTRAINT CHK_METADATA_OBJECT_CACHE_OBJECT_TYPE_CD CHECK (OBJ_TP_CD IN ('PROCEDURE', 'TABLE', 'COLUMN', 'INDEX', 'PK', 'FK', 'FUNCTION', 'VIEW', 'EXTENDED_PROPERTY')),
    CONSTRAINT FK_METADATA_OBJECT_CACHE_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID)
);
GO

CREATE TABLE dbo.METADATA_DEPENDENCY_EDGES (
    DEPD_EDGE_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    SNAP_ID UNIQUEIDENTIFIER NOT NULL,
    FR_OBJ_TP_CD NVARCHAR(30) NOT NULL,
    FR_SCHM_NM NVARCHAR(128) NOT NULL,
    FR_OBJ_NM NVARCHAR(128) NOT NULL,
    DEPD_TP_CD NVARCHAR(30) NOT NULL,
    TO_OBJ_TP_CD NVARCHAR(30) NOT NULL,
    TO_SCHM_NM NVARCHAR(128) NOT NULL,
    TO_OBJ_NM NVARCHAR(128) NOT NULL,
    EVDC_JSON NVARCHAR(MAX) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_DEPENDENCY_EDGES PRIMARY KEY CLUSTERED (DEPD_EDGE_ID),
    CONSTRAINT CHK_METADATA_DEPENDENCY_EDGES_RELATION_TYPE_CD CHECK (DEPD_TP_CD IN ('READS', 'WRITES', 'CALLS', 'REFERENCES', 'USES_TEMP_TABLE', 'USES_DYNAMIC_SQL')),
    CONSTRAINT FK_METADATA_DEPENDENCY_EDGES_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID)
);
GO

/* =========================
   analysis
   ========================= */
CREATE TABLE dbo.ANALYSIS_RESULTS (
    ANLS_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    SNAP_ID UNIQUEIDENTIFIER NOT NULL,
    TRGT_TP_CD NVARCHAR(30) NOT NULL,
    TRGT_SCHM_NM NVARCHAR(128) NOT NULL,
    TRGT_OBJ_NM NVARCHAR(128) NOT NULL,
    ANLS_STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    ANLS_JSON NVARCHAR(MAX) NOT NULL,
    ANLS_DESC NVARCHAR(2000) NULL,
    CONFIDENCE_CD NVARCHAR(20) NULL,
    CNTNT_REF_ID NVARCHAR(500) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ANALYSIS_RESULTS PRIMARY KEY CLUSTERED (ANLS_ID),
    CONSTRAINT CHK_ANALYSIS_RESULTS_TARGET_TYPE_CD CHECK (TRGT_TP_CD IN ('PROCEDURE', 'TABLE', 'VIEW', 'FUNCTION')),
    CONSTRAINT CHK_ANALYSIS_RESULTS_STATUS_CD CHECK (ANLS_STAT_CD IN ('COMPLETED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT CHK_ANALYSIS_RESULTS_CONFIDENCE_CD CHECK (CONFIDENCE_CD IS NULL OR CONFIDENCE_CD IN ('DETERMINISTIC', 'INFERRED', 'REVIEW_REQUIRED')),
    CONSTRAINT FK_ANALYSIS_RESULTS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID),
    CONSTRAINT FK_ANALYSIS_RESULTS_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID)
);
GO

CREATE TABLE dbo.ANALYSIS_EVIDENCE_REFS (
    ANLS_EVDC_REF_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ANLS_ID UNIQUEIDENTIFIER NOT NULL,
    EVDC_TP_CD NVARCHAR(30) NOT NULL,
    OBJ_REF_ID NVARCHAR(500) NOT NULL,
    LOCATOR_TXT NVARCHAR(1000) NULL,
    CONFIDENCE_CD NVARCHAR(20) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ANALYSIS_EVIDENCE_REFS PRIMARY KEY CLUSTERED (ANLS_EVDC_REF_ID),
    CONSTRAINT CHK_ANALYSIS_EVIDENCE_REFS_EVIDENCE_TYPE_CD CHECK (EVDC_TP_CD IN ('OBJECT', 'COLUMN', 'INDEX', 'CONSTRAINT', 'DEFINITION', 'SNAPSHOT')),
    CONSTRAINT CHK_ANALYSIS_EVIDENCE_REFS_CONFIDENCE_CD CHECK (CONFIDENCE_CD IN ('DETERMINISTIC', 'INFERRED', 'REVIEW_REQUIRED')),
    CONSTRAINT FK_ANALYSIS_EVIDENCE_REFS_ANALYSIS FOREIGN KEY (ANLS_ID) REFERENCES dbo.ANALYSIS_RESULTS(ANLS_ID)
);
GO

/* =========================
   artifacts
   ========================= */
CREATE TABLE dbo.ARTIFACTS (
    ARTF_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    ARTF_TP_CD NVARCHAR(40) NOT NULL,
    CUR_STAT_CD NVARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    CUR_ARTF_VER_ID UNIQUEIDENTIFIER NULL,
    TITL NVARCHAR(300) NULL,
    CANON_TRGT_KEY_TXT NVARCHAR(300) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACTS PRIMARY KEY CLUSTERED (ARTF_ID),
    CONSTRAINT CHK_ARTIFACTS_TYPE_CD CHECK (
        ARTF_TP_CD IN (
            'SP_ANALYSIS_DOC',
            'DEPENDENCY_REPORT',
            'METADATA_QUERY_RESULT',
            'SCHEMA_ENRICHMENT_RESULT',
            'MAPPER_XML',
            'MAPPER_INTERFACE',
            'SERVICE_DRAFT',
            'DTO_DRAFT',
            'VALIDATION_REPORT',
            'APPROVAL_LOG',
            'VO_DRAFT',
            'MODEL_DRAFT',
            'DDL_DRAFT'
        )
    ),
    CONSTRAINT CHK_ARTIFACTS_STATUS_CD CHECK (CUR_STAT_CD IN ('DRAFT', 'VALIDATED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT FK_ARTIFACTS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

CREATE TABLE dbo.ARTIFACT_VERSIONS (
    ARTF_VER_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ARTF_ID UNIQUEIDENTIFIER NOT NULL,
    VER_SEQ_NO INT NOT NULL,
    CNTNT_TP_CD NVARCHAR(20) NOT NULL,
    CNTNT_REF_ID NVARCHAR(500) NULL,
    CNTNT_TXT NVARCHAR(MAX) NULL,
    CHK_SUM_SHA256_VAL NVARCHAR(64) NULL,
    SNAP_ID UNIQUEIDENTIFIER NULL,
    ANLS_ID UNIQUEIDENTIFIER NULL,
    RGST_BINDING_JSON NVARCHAR(MAX) NULL,
    EVDC_JSON NVARCHAR(MAX) NULL,
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACT_VERSIONS PRIMARY KEY CLUSTERED (ARTF_VER_ID),
    CONSTRAINT UQ_ARTIFACT_VERSIONS UNIQUE (ARTF_ID, VER_SEQ_NO),
    CONSTRAINT CHK_ARTIFACT_VERSIONS_CONTENT_TYPE_CD CHECK (CNTNT_TP_CD IN ('TEXT', 'MARKDOWN', 'XML', 'JAVA', 'JSON', 'SQL', 'YAML')),
    CONSTRAINT FK_ARTIFACT_VERSIONS_ARTIFACT FOREIGN KEY (ARTF_ID) REFERENCES dbo.ARTIFACTS(ARTF_ID),
    CONSTRAINT FK_ARTIFACT_VERSIONS_SNAPSHOT FOREIGN KEY (SNAP_ID) REFERENCES dbo.METADATA_SNAPSHOTS(SNAP_ID),
    CONSTRAINT FK_ARTIFACT_VERSIONS_ANALYSIS FOREIGN KEY (ANLS_ID) REFERENCES dbo.ANALYSIS_RESULTS(ANLS_ID),
    CONSTRAINT FK_ARTIFACT_VERSIONS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

ALTER TABLE dbo.ARTIFACTS
ADD CONSTRAINT FK_ARTIFACTS_CURRENT_VERSION FOREIGN KEY (CUR_ARTF_VER_ID)
    REFERENCES dbo.ARTIFACT_VERSIONS(ARTF_VER_ID);
GO

CREATE TABLE dbo.ARTIFACT_VALIDATION_REPORTS (
    VLDT_RSLT_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ARTF_VER_ID UNIQUEIDENTIFIER NOT NULL,
    VLDT_PRFL_NM NVARCHAR(150) NULL,
    VLDT_RSLT_CD NVARCHAR(10) NOT NULL,
    RSLT_JSON NVARCHAR(MAX) NOT NULL,
    MISSING_EVDC_JSON NVARCHAR(MAX) NULL,
    MANUAL_RVWR_POINTS_JSON NVARCHAR(MAX) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CRE_USR_ID UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_ARTIFACT_VALIDATION_REPORTS PRIMARY KEY CLUSTERED (VLDT_RSLT_ID),
    CONSTRAINT CHK_ARTIFACT_VALIDATION_REPORTS_PASS_FAIL_CD CHECK (VLDT_RSLT_CD IN ('PASS', 'FAIL')),
    CONSTRAINT FK_ARTIFACT_VALIDATION_REPORTS_ARTIFACT_VERSION FOREIGN KEY (ARTF_VER_ID) REFERENCES dbo.ARTIFACT_VERSIONS(ARTF_VER_ID),
    CONSTRAINT FK_ARTIFACT_VALIDATION_REPORTS_CREATED_BY FOREIGN KEY (CRE_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TABLE dbo.ARTIFACT_APPROVAL_RECORDS (
    APRV_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ARTF_VER_ID UNIQUEIDENTIFIER NOT NULL,
    RVWR_USR_ID UNIQUEIDENTIFIER NOT NULL,
    DCISN_CD NVARCHAR(20) NOT NULL,
    RVWR_CNTNT NVARCHAR(MAX) NULL,
    CHKLST_RSLT_JSON NVARCHAR(MAX) NULL,
    APRV_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ARTIFACT_APPROVAL_RECORDS PRIMARY KEY CLUSTERED (APRV_ID),
    CONSTRAINT CHK_ARTIFACT_APPROVAL_RECORDS_DECISION_CD CHECK (DCISN_CD IN ('APPROVED', 'REJECTED')),
    CONSTRAINT FK_ARTIFACT_APPROVAL_RECORDS_ARTIFACT_VERSION FOREIGN KEY (ARTF_VER_ID) REFERENCES dbo.ARTIFACT_VERSIONS(ARTF_VER_ID),
    CONSTRAINT FK_ARTIFACT_APPROVAL_RECORDS_REVIEWER FOREIGN KEY (RVWR_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

CREATE TRIGGER dbo.TRG_ARTIFACTS_BLOCK_P36_RETIRED_TYPES
ON dbo.ARTIFACTS
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted AS i
        LEFT JOIN deleted AS d
          ON d.ARTF_ID = i.ARTF_ID
        WHERE i.ARTF_TP_CD IN ('VO_DRAFT', 'MODEL_DRAFT', 'DDL_DRAFT')
          AND (
              d.ARTF_ID IS NULL
              OR ISNULL(d.ARTF_TP_CD, '') <> i.ARTF_TP_CD
          )
    )
    BEGIN
        THROW 51036,
            'P36 retired artifact types are historical-only. New VO_DRAFT, MODEL_DRAFT, or DDL_DRAFT artifacts are blocked.',
            1;
    END;
END;
GO

/* =========================
   runtime traces
   ========================= */
CREATE TABLE dbo.AGENT_RUNS (
    AGNT_RUN_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    AGNT_TP_CD NVARCHAR(60) NOT NULL,
    STAT_CD NVARCHAR(20) NOT NULL,
    TRGT_REF_TXT NVARCHAR(500) NOT NULL,
    CANON_TRGT_KEY_TXT NVARCHAR(300) NULL,
    SMRY_TXT NVARCHAR(1000) NULL,
    STRUCTURED_OUTPUT_JSON NVARCHAR(MAX) NOT NULL,
    MODEL_INVOCATION_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AGENT_RUNS PRIMARY KEY CLUSTERED (AGNT_RUN_ID),
    CONSTRAINT CHK_AGENT_RUNS_STATUS_CD CHECK (STAT_CD IN ('SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT FK_AGENT_RUNS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

CREATE TABLE dbo.MODEL_INVOCATIONS (
    MDL_INVC_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    AGNT_RUN_ID UNIQUEIDENTIFIER NOT NULL,
    PRVDR_NM NVARCHAR(60) NOT NULL,
    MDL_NM NVARCHAR(120) NOT NULL,
    MDL_PRFL_ID NVARCHAR(120) NOT NULL,
    RSNG_EFFORT_CD NVARCHAR(20) NULL,
    PROMPT_VER_REF NVARCHAR(200) NOT NULL,
    OUTPUT_SCHEMA_VER_REF NVARCHAR(200) NOT NULL,
    INPUT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    PROMPT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    OUTPUT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    TOKEN_USAGE_JSON NVARCHAR(MAX) NULL,
    LATENCY_MS INT NULL,
    STAT_CD NVARCHAR(20) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_MODEL_INVOCATIONS PRIMARY KEY CLUSTERED (MDL_INVC_ID),
    CONSTRAINT CHK_MODEL_INVOCATIONS_STATUS_CD CHECK (STAT_CD IN ('SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT CHK_MODEL_INVOCATIONS_REASONING_EFFORT_CD CHECK (
        RSNG_EFFORT_CD IS NULL OR RSNG_EFFORT_CD IN ('none', 'low', 'medium', 'high', 'xhigh')
    ),
    CONSTRAINT FK_MODEL_INVOCATIONS_AGENT_RUN FOREIGN KEY (AGNT_RUN_ID)
        REFERENCES dbo.AGENT_RUNS(AGNT_RUN_ID)
);
GO

/* =========================
   knowledge assets
   ========================= */
CREATE TABLE dbo.KNOWLEDGE_ASSETS (
    ASST_ID NVARCHAR(80) NOT NULL,
    ASST_KIND_CD NVARCHAR(40) NOT NULL,
    DB_PRFL_REF_TXT NVARCHAR(150) NOT NULL,
    TRGT_TP_CD NVARCHAR(40) NOT NULL,
    TRGT_SCHM_NM NVARCHAR(128) NOT NULL DEFAULT '',
    TRGT_OBJ_NM NVARCHAR(128) NOT NULL,
    LOGICAL_KEY_TXT NVARCHAR(600) NOT NULL,
    CANON_TRGT_KEY_TXT NVARCHAR(300) NULL,
    CUR_VER_ID NVARCHAR(80) NULL,
    CUR_VER_NO INT NOT NULL DEFAULT 0,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NULL,
    SRC_JOB_ID NVARCHAR(80) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_ASSETS PRIMARY KEY CLUSTERED (ASST_ID),
    CONSTRAINT UQ_KNOWLEDGE_ASSETS_LOGICAL_KEY UNIQUE (LOGICAL_KEY_TXT),
    CONSTRAINT CHK_KNOWLEDGE_ASSETS_KIND CHECK (
        ASST_KIND_CD IN (
            'SP_ANALYSIS',
            'DEPENDENCY_EVIDENCE',
            'METADATA_PROFILE',
            'DTO_READINESS',
            'CANONICAL_ANALYSIS'
        )
    )
);
GO

CREATE TABLE dbo.KNOWLEDGE_ASSET_VERSIONS (
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    VER_SEQ_NO INT NOT NULL,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    SRC_JOB_ID NVARCHAR(80) NULL,
    LIFECYCLE_STAT_CD NVARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    LIFECYCLE_NOTE_JSON NVARCHAR(MAX) NOT NULL DEFAULT '{}',
    ARCHV_DTM DATETIME2(3) NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_ASSET_VERSIONS PRIMARY KEY CLUSTERED (ASST_VER_ID),
    CONSTRAINT UQ_KNOWLEDGE_ASSET_VERSIONS UNIQUE (ASST_ID, VER_SEQ_NO),
    CONSTRAINT UQ_KNOWLEDGE_ASSET_VERSIONS_HASH UNIQUE (ASST_ID, CNTNT_HASH_SHA256_VAL),
    CONSTRAINT CHK_KNOWLEDGE_ASSET_VERSIONS_LIFECYCLE CHECK (
        LIFECYCLE_STAT_CD IN ('DRAFT', 'REVIEW_REQUIRED', 'ARCHIVED')
    ),
    CONSTRAINT FK_KNOWLEDGE_ASSET_VERSIONS_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID)
);
GO

ALTER TABLE dbo.KNOWLEDGE_ASSETS
ADD CONSTRAINT FK_KNOWLEDGE_ASSETS_CURRENT_VERSION FOREIGN KEY (CUR_VER_ID)
    REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID);
GO

CREATE TABLE dbo.KNOWLEDGE_FACTS (
    FACT_ID NVARCHAR(220) NOT NULL,
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    FACT_TP_CD NVARCHAR(80) NOT NULL,
    OBJ_REF_TXT NVARCHAR(500) NOT NULL,
    SMRY_TXT NVARCHAR(1000) NOT NULL,
    STAT_CD NVARCHAR(30) NOT NULL,
    EVDC_REFS_JSON NVARCHAR(MAX) NOT NULL,
    PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_FACTS PRIMARY KEY CLUSTERED (ASST_VER_ID, FACT_ID),
    CONSTRAINT CHK_KNOWLEDGE_FACTS_STATUS CHECK (
        STAT_CD IN ('OBSERVED', 'INFERRED_DESCRIPTION', 'REVIEW_REQUIRED')
    ),
    CONSTRAINT FK_KNOWLEDGE_FACTS_VERSION FOREIGN KEY (ASST_VER_ID)
        REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID),
    CONSTRAINT FK_KNOWLEDGE_FACTS_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID)
);
GO

CREATE TABLE dbo.KNOWLEDGE_FACT_EDGES (
    EDGE_ID NVARCHAR(220) NOT NULL,
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    FROM_FACT_ID NVARCHAR(220) NOT NULL,
    TO_FACT_ID NVARCHAR(220) NOT NULL,
    EDGE_TP_CD NVARCHAR(40) NOT NULL,
    EVDC_REFS_JSON NVARCHAR(MAX) NOT NULL,
    PAYLD_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_FACT_EDGES PRIMARY KEY CLUSTERED (ASST_VER_ID, EDGE_ID),
    CONSTRAINT CHK_KNOWLEDGE_FACT_EDGES_TYPE CHECK (
        EDGE_TP_CD IN (
            'DEPENDS_ON',
            'DERIVED_FROM',
            'SUPPORTS',
            'READS',
            'WRITES',
            'CALLS',
            'FK_TO',
            'DTO_FIELD_OF'
        )
    ),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_VERSION FOREIGN KEY (ASST_VER_ID)
        REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_FROM_FACT FOREIGN KEY (ASST_VER_ID, FROM_FACT_ID)
        REFERENCES dbo.KNOWLEDGE_FACTS(ASST_VER_ID, FACT_ID),
    CONSTRAINT FK_KNOWLEDGE_FACT_EDGES_TO_FACT FOREIGN KEY (ASST_VER_ID, TO_FACT_ID)
        REFERENCES dbo.KNOWLEDGE_FACTS(ASST_VER_ID, FACT_ID)
);
GO

CREATE TABLE dbo.KNOWLEDGE_ASSET_JOB_LINKS (
    JOB_REF_ID NVARCHAR(80) NOT NULL,
    ASST_ID NVARCHAR(80) NOT NULL,
    ASST_VER_ID NVARCHAR(80) NOT NULL,
    LINK_TP_CD NVARCHAR(30) NOT NULL DEFAULT 'SOURCE',
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_ASSET_JOB_LINKS PRIMARY KEY CLUSTERED (JOB_REF_ID, ASST_ID, ASST_VER_ID),
    CONSTRAINT CHK_KNOWLEDGE_ASSET_JOB_LINKS_TYPE CHECK (LINK_TP_CD IN ('SOURCE')),
    CONSTRAINT FK_KNOWLEDGE_ASSET_JOB_LINKS_ASSET FOREIGN KEY (ASST_ID)
        REFERENCES dbo.KNOWLEDGE_ASSETS(ASST_ID),
    CONSTRAINT FK_KNOWLEDGE_ASSET_JOB_LINKS_VERSION FOREIGN KEY (ASST_VER_ID)
        REFERENCES dbo.KNOWLEDGE_ASSET_VERSIONS(ASST_VER_ID)
);
GO

CREATE TABLE dbo.KNOWLEDGE_EXPORTS (
    EXPRT_ID NVARCHAR(80) NOT NULL,
    FMT_CD NVARCHAR(30) NOT NULL,
    CNTNT_TP_TXT NVARCHAR(100) NOT NULL,
    CNTNT_TXT NVARCHAR(MAX) NOT NULL,
    CNTNT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    ASST_IDS_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_KNOWLEDGE_EXPORTS PRIMARY KEY CLUSTERED (EXPRT_ID),
    CONSTRAINT CHK_KNOWLEDGE_EXPORTS_FORMAT CHECK (FMT_CD IN ('JSONL', 'GRAPH_JSON'))
);
GO

/* =========================
   durable metadata runs
   ========================= */
CREATE TABLE dbo.METADATA_ANALYSIS_RUNS (
    RUN_ID NVARCHAR(80) NOT NULL,
    STAT_CD NVARCHAR(30) NOT NULL,
    REQUEST_JSON NVARCHAR(MAX) NOT NULL,
    ANALYSIS_JSON NVARCHAR(MAX) NULL,
    ERR_JSON NVARCHAR(MAX) NULL,
    SUBMITTED_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    START_DTM DATETIME2(3) NULL,
    COMPLETED_DTM DATETIME2(3) NULL,
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_ANALYSIS_RUNS PRIMARY KEY CLUSTERED (RUN_ID),
    CONSTRAINT CHK_METADATA_ANALYSIS_RUNS_STATUS CHECK (
        STAT_CD IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT CHK_METADATA_ANALYSIS_RUNS_REQUEST_JSON CHECK (ISJSON(REQUEST_JSON) = 1),
    CONSTRAINT CHK_METADATA_ANALYSIS_RUNS_ANALYSIS_JSON CHECK (
        ANALYSIS_JSON IS NULL OR ISJSON(ANALYSIS_JSON) = 1
    ),
    CONSTRAINT CHK_METADATA_ANALYSIS_RUNS_ERR_JSON CHECK (
        ERR_JSON IS NULL OR ISJSON(ERR_JSON) = 1
    )
);
GO

CREATE TABLE dbo.METADATA_DESIGN_RUNS (
    RUN_ID NVARCHAR(80) NOT NULL,
    CONVERSATION_ID NVARCHAR(80) NOT NULL,
    STAT_CD NVARCHAR(30) NOT NULL,
    REQUEST_JSON NVARCHAR(MAX) NOT NULL,
    RESULT_JSON NVARCHAR(MAX) NULL,
    ERR_JSON NVARCHAR(MAX) NULL,
    SUBMITTED_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    START_DTM DATETIME2(3) NULL,
    COMPLETED_DTM DATETIME2(3) NULL,
    UPD_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_METADATA_DESIGN_RUNS PRIMARY KEY CLUSTERED (RUN_ID),
    CONSTRAINT CHK_METADATA_DESIGN_RUNS_STATUS CHECK (
        STAT_CD IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT CHK_METADATA_DESIGN_RUNS_REQUEST_JSON CHECK (ISJSON(REQUEST_JSON) = 1),
    CONSTRAINT CHK_METADATA_DESIGN_RUNS_RESULT_JSON CHECK (
        RESULT_JSON IS NULL OR ISJSON(RESULT_JSON) = 1
    ),
    CONSTRAINT CHK_METADATA_DESIGN_RUNS_ERR_JSON CHECK (
        ERR_JSON IS NULL OR ISJSON(ERR_JSON) = 1
    )
);
GO

/* =========================
   audit
   ========================= */
CREATE TABLE dbo.AUDIT_EVENTS (
    AUDT_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ACTR_USR_ID UNIQUEIDENTIFIER NULL,
    ACTION_CD NVARCHAR(100) NOT NULL,
    TRGT_TP_CD NVARCHAR(50) NOT NULL,
    TRGT_REF_ID NVARCHAR(100) NOT NULL,
    TRC_ID NVARCHAR(100) NULL,
    PAYLD_JSON NVARCHAR(MAX) NULL,
    AUDT_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AUDIT_EVENTS PRIMARY KEY CLUSTERED (AUDT_ID),
    CONSTRAINT FK_AUDIT_EVENTS_ACTOR FOREIGN KEY (ACTR_USR_ID) REFERENCES dbo.AUTH_USERS(USR_ID)
);
GO

/* =========================
   recommended indexes
   ========================= */
CREATE INDEX IX_CORE_WORK_REQUESTS_TYPE_STATUS_SUBMITTED_AT
    ON dbo.CORE_WORK_REQUESTS(REQ_TP_CD, CUR_STAT_CD, SUBMITTED_DTM DESC);
GO

CREATE INDEX IX_CORE_WORK_REQUESTS_CANON_TARGET_SUBMITTED
    ON dbo.CORE_WORK_REQUESTS(CANON_TRGT_KEY_TXT, SUBMITTED_DTM DESC)
    WHERE CANON_TRGT_KEY_TXT IS NOT NULL;
GO

CREATE INDEX IX_CORE_JOBS_REQUEST_STATUS
    ON dbo.CORE_JOBS(REQ_ID, CUR_STAT_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_CORE_JOBS_CANON_TARGET_CREATED
    ON dbo.CORE_JOBS(CANON_TRGT_KEY_TXT, CRE_DTM DESC)
    WHERE CANON_TRGT_KEY_TXT IS NOT NULL;
GO

CREATE INDEX IX_CORE_JOB_STEPS_JOB_STEP_TYPE
    ON dbo.CORE_JOB_STEPS(JOB_ID, STEP_TP_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_REGISTRY_VERSIONS_ITEM_PUBLISHED
    ON dbo.REGISTRY_VERSIONS(RGST_ITEM_ID, PBLC_YN, VER_SEQ_NO DESC);
GO

CREATE INDEX IX_METADATA_SNAPSHOTS_PROFILE_CAPTURED
    ON dbo.METADATA_SNAPSHOTS(DB_PRFL_ID, CAPTURED_DTM DESC);
GO

CREATE INDEX IX_METADATA_OBJECT_CACHE_SNAPSHOT_TYPE_NAME
    ON dbo.METADATA_OBJECT_CACHE(SNAP_ID, OBJ_TP_CD, SCHM_NM, OBJ_NM);
GO

CREATE INDEX IX_METADATA_DEPENDENCY_EDGES_SNAPSHOT_FROM
    ON dbo.METADATA_DEPENDENCY_EDGES(SNAP_ID, FR_SCHM_NM, FR_OBJ_NM, DEPD_TP_CD);
GO

CREATE INDEX IX_METADATA_DEPENDENCY_EDGES_SNAPSHOT_TO
    ON dbo.METADATA_DEPENDENCY_EDGES(SNAP_ID, TO_SCHM_NM, TO_OBJ_NM, DEPD_TP_CD);
GO

CREATE INDEX IX_ANALYSIS_RESULTS_JOB_TARGET
    ON dbo.ANALYSIS_RESULTS(JOB_ID, TRGT_SCHM_NM, TRGT_OBJ_NM, CRE_DTM DESC);
GO

CREATE INDEX IX_ARTIFACTS_JOB_TYPE_STATUS
    ON dbo.ARTIFACTS(JOB_ID, ARTF_TP_CD, CUR_STAT_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_ARTIFACTS_JOB_CANON_TARGET
    ON dbo.ARTIFACTS(JOB_ID, CANON_TRGT_KEY_TXT, CRE_DTM DESC)
    WHERE CANON_TRGT_KEY_TXT IS NOT NULL;
GO

CREATE INDEX IX_ARTIFACT_VERSIONS_ARTIFACT_VERSION_NO
    ON dbo.ARTIFACT_VERSIONS(ARTF_ID, VER_SEQ_NO DESC);
GO

CREATE INDEX IX_ARTIFACT_VALIDATION_REPORTS_ARTIFACT_VERSION
    ON dbo.ARTIFACT_VALIDATION_REPORTS(ARTF_VER_ID, CRE_DTM DESC);
GO

CREATE INDEX IX_ARTIFACT_APPROVAL_RECORDS_ARTIFACT_VERSION
    ON dbo.ARTIFACT_APPROVAL_RECORDS(ARTF_VER_ID, APRV_DTM DESC);
GO

CREATE INDEX IX_AGENT_RUNS_JOB_CANON_TARGET
    ON dbo.AGENT_RUNS(JOB_ID, CANON_TRGT_KEY_TXT, CRE_DTM DESC)
    WHERE CANON_TRGT_KEY_TXT IS NOT NULL;
GO

CREATE INDEX IX_KNOWLEDGE_ASSETS_JOB
    ON dbo.KNOWLEDGE_ASSETS(SRC_JOB_ID, UPD_DTM DESC);
GO

CREATE INDEX IX_KNOWLEDGE_ASSETS_TARGET
    ON dbo.KNOWLEDGE_ASSETS(DB_PRFL_REF_TXT, TRGT_TP_CD, TRGT_SCHM_NM, TRGT_OBJ_NM);
GO

CREATE INDEX IX_KNOWLEDGE_ASSETS_CANON_TARGET
    ON dbo.KNOWLEDGE_ASSETS(CANON_TRGT_KEY_TXT, UPD_DTM DESC)
    WHERE CANON_TRGT_KEY_TXT IS NOT NULL;
GO

CREATE INDEX IX_KNOWLEDGE_FACTS_OBJECT
    ON dbo.KNOWLEDGE_FACTS(OBJ_REF_TXT, FACT_TP_CD);
GO

CREATE INDEX IX_KNOWLEDGE_FACTS_SEARCH
    ON dbo.KNOWLEDGE_FACTS(OBJ_REF_TXT, FACT_TP_CD, STAT_CD);
GO

CREATE INDEX IX_KNOWLEDGE_ASSET_VERSIONS_LIFECYCLE
    ON dbo.KNOWLEDGE_ASSET_VERSIONS(LIFECYCLE_STAT_CD, CRE_DTM DESC);
GO

CREATE INDEX IX_KNOWLEDGE_ASSET_JOB_LINKS_JOB
    ON dbo.KNOWLEDGE_ASSET_JOB_LINKS(JOB_REF_ID, CRE_DTM DESC);
GO

CREATE INDEX IX_KNOWLEDGE_EXPORTS_CREATED
    ON dbo.KNOWLEDGE_EXPORTS(CRE_DTM DESC);
GO

CREATE INDEX IX_METADATA_ANALYSIS_RUNS_STATUS
    ON dbo.METADATA_ANALYSIS_RUNS(STAT_CD, UPD_DTM DESC);
GO

CREATE INDEX IX_METADATA_ANALYSIS_RUNS_SUBMITTED
    ON dbo.METADATA_ANALYSIS_RUNS(SUBMITTED_DTM DESC);
GO

CREATE INDEX IX_METADATA_DESIGN_RUNS_STATUS
    ON dbo.METADATA_DESIGN_RUNS(STAT_CD, UPD_DTM DESC);
GO

CREATE INDEX IX_METADATA_DESIGN_RUNS_CONVERSATION
    ON dbo.METADATA_DESIGN_RUNS(CONVERSATION_ID, SUBMITTED_DTM DESC);
GO

CREATE INDEX IX_METADATA_DESIGN_RUNS_SUBMITTED
    ON dbo.METADATA_DESIGN_RUNS(SUBMITTED_DTM DESC);
GO

CREATE INDEX IX_AUDIT_EVENTS_OCCURRED_AT
    ON dbo.AUDIT_EVENTS(AUDT_DTM DESC);
GO

CREATE INDEX IX_AUDIT_EVENTS_ACTOR_ACTION
    ON dbo.AUDIT_EVENTS(ACTR_USR_ID, ACTION_CD, AUDT_DTM DESC);
GO
