/*
  MSSQL Analysis Agent Platform
  Platform DB DDL Draft v3: Agent Runtime / Model Invocation Trace

  Manual apply only. Codex must not execute this file automatically.
  Raw prompt text, raw stored procedure definition text, and raw model response text are
  intentionally absent. Store hashes plus schema-valid structured output only.
*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE dbo.AGENT_RUNS (
    AGNT_RUN_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    JOB_ID UNIQUEIDENTIFIER NOT NULL,
    AGNT_TP_CD NVARCHAR(60) NOT NULL,
    STAT_CD NVARCHAR(20) NOT NULL,
    TRGT_REF_TXT NVARCHAR(500) NOT NULL,
    SMRY_TXT NVARCHAR(1000) NULL,
    STRUCTURED_OUTPUT_JSON NVARCHAR(MAX) NOT NULL,
    MODEL_INVOCATION_JSON NVARCHAR(MAX) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_AGENT_RUNS PRIMARY KEY CLUSTERED (AGNT_RUN_ID),
    CONSTRAINT CHK_AGENT_RUNS_STATUS_CD CHECK (STAT_CD IN ('SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT FK_AGENT_RUNS_JOB FOREIGN KEY (JOB_ID) REFERENCES dbo.CORE_JOBS(JOB_ID)
);
GO

CREATE TABLE dbo.MODEL_INVOCATIONS (
    MDL_INVC_ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    AGNT_RUN_ID UNIQUEIDENTIFIER NOT NULL,
    PRVDR_NM NVARCHAR(60) NOT NULL,
    MDL_NM NVARCHAR(120) NOT NULL,
    MDL_PRFL_ID NVARCHAR(120) NOT NULL,
    RSNG_EFFORT_CD NVARCHAR(20) NULL,
    PROMPT_VER_REF NVARCHAR(200) NOT NULL,
    OUTPUT_SCHEMA_VER_REF NVARCHAR(200) NOT NULL,
    INPUT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    PROMPT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    OUTPUT_HASH_SHA256_VAL NVARCHAR(64) NOT NULL,
    TOKEN_USAGE_JSON NVARCHAR(MAX) NULL,
    LATENCY_MS INT NULL,
    STAT_CD NVARCHAR(20) NOT NULL,
    CRE_DTM DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_MODEL_INVOCATIONS PRIMARY KEY CLUSTERED (MDL_INVC_ID),
    CONSTRAINT CHK_MODEL_INVOCATIONS_STATUS_CD CHECK (STAT_CD IN ('SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT CHK_MODEL_INVOCATIONS_REASONING_EFFORT_CD CHECK (
        RSNG_EFFORT_CD IS NULL OR RSNG_EFFORT_CD IN ('none', 'low', 'medium', 'high', 'xhigh')
    ),
    CONSTRAINT FK_MODEL_INVOCATIONS_AGENT_RUN FOREIGN KEY (AGNT_RUN_ID)
        REFERENCES dbo.AGENT_RUNS(AGNT_RUN_ID)
);
GO
